### ISSUE TITLE
Incorrect display of a php serialized data onto textedit fields.

### ISSUE THREAD

**Issue by any626** [therecipe/qt#368] opened 2017-06-18 04:45 UTC
Hey,
I'm trying to display a string from redis that happens to be php serialized data onto a textedit field. But only the string up to the first asterisk (*) is displayed. I've printed the data onto the terminal and it appears fine. I've also tried hard coding an asterisk to the textedit and it displays it fine.

Any help would be appreciated, thanks!

**Comment by therecipe** [comment] 2017-06-18 17:16
Hey

Are you setting the text with `setText`? If so, could you maybe test it with `setPlainText` as well?
Also do you call `setText` from another go routine? And could you maybe provide a minimal example, so that I can reproduce this?

**Comment by any626** [comment] 2017-06-18 20:22
I have tried both setText and setPlainText with the same result.
Here is an example without the use of redis. I used []uint8 since that was the type received from redis.
`package main

import (
        "github.com/therecipe/qt/widgets"
        "os"
)

func main() {
        widgets.NewQApplication(len(os.Args), os.Args)

        textEdit := widgets.NewQTextEdit(nil)
        textEdit.SetMinimumSize2(400, 400)
        textEdit.SetPlainText(string([]uint8{42, 0, 116, 101, 115, 116})) // should display "*test"
        textEdit.Show()

        widgets.QApplication_Exec()

}`
After looking up the php serialize docs, it seems that it inserts a null byte between the '*'.
Here is the docs for it http://php.net/manual/en/function.serialize.php

It seems that qt Text fields are not handling the null characters properly.

**Comment by therecipe** [comment] 2017-06-18 21:27
Ah, yeah I looked into it and the textfield seems to be able to handle strings containing null bytes.
The issue is just that the real string is truncated during the conversion from a Go string to a QString, because the length info is "lost" along the way. But I will fix it.

**Comment by therecipe** [comment] 2017-06-20 20:49
Okay, should be fixed now with: https://github.com/therecipe/qt/commit/c6cb74d45e468dce508f47aa87d51793d904a9ad

**Comment by any626** [comment] 2017-06-20 21:11
Works perfectly! Thank you!

**Closed** 2017-06-20 21:11 UTC
