### ISSUE TITLE
iOS QML Import missing

### ISSUE THREAD

**Issue by mikehawkes** [therecipe/qt#733] opened 2018-11-14 14:00 UTC
Hi

Trying to run `qtdeploy build ios` and I'm getting a compile fail - 
```
env= error="exit status 1" name="compile wrapper for ios (arm64) on darwin" clang: error: no such file or directory: 'ios_qml_plugin_import.cpp'
```

I do get an ios_plugin_import.cpp appearing in the deploy/ios subdirectory, but can's see the qml_plugin file at all.

Any pointers gratefully received.
Cheers
Mike

(MacOS 10.14.1, QT5.11.1, Xcode Version 10.1 (10B61), Go 1.11.1)

**Comment by therecipe** [comment] 2018-11-17 16:56
Hey

I looked into this and your issue should be fixed now with https://github.com/therecipe/qt/commit/4cdafbc0fd4438b50c3e48422cfb0e1c7567a9f4
As well as some other issue caused by linking against the wrong iOS SDK.

**Comment by therecipe** [comment] 2019-01-03 19:19
Will close this now, please reopen if it is still relevant

**Closed by therecipe** 2019-01-03 19:19 UTC
