### ISSUE TITLE
when run qtsetup.exe in windows(amd64),mklink fail

### ISSUE THREAD

**Issue by Applejan** [therecipe/qt#672] opened 2018-07-22 04:41 UTC
mklink can be run in a same volume disk, if GOPATH is not in c：prep.go  line 35-line 37 won't run successful.

**Comment by therecipe** [comment] 2019-01-03 19:00
Will close this now, since I recently replace `mklink` is with `os.Link` https://github.com/therecipe/qt/blob/master/internal/cmd/setup/prep.go#L36

However, I haven't tried to reproduce the issue, so please reopen if this is still relevant.

**Closed by therecipe** 2019-01-03 19:00 UTC
