### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by Kutabe** [therecipe/qt#300] opened 2017-04-26 06:20 UTC
Hello, I switched to windows and can not build qt on it.
I use MSYS2. Here is what I get:
```
ku7ab@windows ~ % qtsetup test windows
time="2017-04-26T09:12:05+03:00" level=info msg="running: 'qtsetup test windows' [docker=false]"
time="2017-04-26T09:12:05+03:00" level=info msg="testing qml\application"
time="2017-04-26T09:12:34+03:00" level=error msg="failed to run command" cmd="go build -p 4 -v -ldflags="-s" "-w" "-H=windowsgui" -o C:\Users\ku7ab\Documents\Go\src\github.com\therecipe\qt\internal\examples\qml\application\deploy\windows\application.exe -tags="minimal"" env="CGO_ENABLED=1 PATH=C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl;C;C:\Users\ku7ab\Documents\Go\bin;C:\Go\bin GOARCH=amd64 GOPATH=C:\Users\ku7ab\Documents\Go\ GOROOT=C:\Go\ TMP=C:\msys64\tmp TEMP=C:\msys64\tmp GOOS=windows" error="exit status 2" func=RunCmd name="build for windows on windows"
github.com/therecipe/qt
runtime/cgo
# runtime/cgo
C:\Go\src\runtime\cgo\gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':
C:\Go\src\runtime\cgo\gcc_libinit_windows.c:56:12: error: implicit declaration of function '_beginthread' [-Werror=implicit-function-declaration]
  thandle = _beginthread(func, 0, arg);
            ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Build and setup passed.
Env variables:
`QT_MSYS2=true`
`QT_MSYS2_DIR=/c/msys64`
`QT_MSYS2_ARCH=amd64`
`QT_MSYS2_STATIC=true`

**Comment by therecipe** [comment] 2017-04-26 19:13
Hey

I will look into it.

**Comment by Kutabe** [comment] 2017-04-28 13:07
I've tried to use `mingw-w64-x86_64-gcc` compiler instead of `gcc`, and I get different error:
```
ku7ab@windows ~ % qtsetup
time="2017-04-28T15:55:03+03:00" level=info msg="running: 'qtsetup prep'"
time="2017-04-28T15:55:03+03:00" level=info msg="running: 'qtsetup check windows' [docker=false]"
time="2017-04-28T15:55:03+03:00" level=info msg="GOOS:                        'windows'"
time="2017-04-28T15:55:03+03:00" level=info msg="GOARCH:                      'amd64'"
time="2017-04-28T15:55:03+03:00" level=info msg="GOVERSION:                   'go1.8.1'"
time="2017-04-28T15:55:03+03:00" level=info msg="GOROOT:                   *  'C:\Go\'"
time="2017-04-28T15:55:03+03:00" level=info msg="GOPATH:                   *  'C:\Users\ku7ab\Documents\Go\'"
time="2017-04-28T15:55:03+03:00" level=info msg="GOBIN:                       'C:\Users\ku7ab\Documents\Go\bin'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_HASH:                     '118c850fc3e17743687b9404abe053e3ac844b43'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_VERSION:                  '5.8.0'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_VERSION_MAJOR:            '5.8'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_DIR:                      'C:\Qt\Qt5.8.0'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_STUB:                     'true'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_DEBUG:                    'false'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_WEBKIT:                   'false'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_MSYS2:                 *  'true'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_MSYS2_DIR:             *  'C:\BIN\MSYS2\mingw64'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_MSYS2_ARCH:            *  'amd64'"
time="2017-04-28T15:55:03+03:00" level=info msg="QT_MSYS2_STATIC:          *  'true'"
time="2017-04-28T15:55:03+03:00" level=info msg="running: 'qtsetup generate windows' [docker=false]"
time="2017-04-28T15:55:16+03:00" level=info msg="generating stub qt/core"
time="2017-04-28T15:55:20+03:00" level=info msg="generating stub qt/androidextras"
time="2017-04-28T15:55:20+03:00" level=info msg="generating stub qt/gui"
time="2017-04-28T15:55:25+03:00" level=info msg="generating stub qt/network"
time="2017-04-28T15:55:26+03:00" level=info msg="generating stub qt/xml"
time="2017-04-28T15:55:26+03:00" level=info msg="generating stub qt/dbus"
time="2017-04-28T15:55:27+03:00" level=info msg="generating stub qt/nfc"
time="2017-04-28T15:55:27+03:00" level=info msg="generating stub qt/script"
time="2017-04-28T15:55:27+03:00" level=info msg="generating stub qt/sensors"
time="2017-04-28T15:55:28+03:00" level=info msg="generating stub qt/positioning"
time="2017-04-28T15:55:28+03:00" level=info msg="generating stub qt/widgets"
time="2017-04-28T15:55:38+03:00" level=info msg="generating stub qt/sql"
time="2017-04-28T15:55:39+03:00" level=info msg="generating stub qt/qml"
time="2017-04-28T15:55:39+03:00" level=info msg="generating stub qt/websockets"
time="2017-04-28T15:55:39+03:00" level=info msg="generating stub qt/xmlpatterns"
time="2017-04-28T15:55:40+03:00" level=info msg="generating stub qt/bluetooth"
time="2017-04-28T15:55:40+03:00" level=info msg="generating stub qt/webchannel"
time="2017-04-28T15:55:40+03:00" level=info msg="generating stub qt/svg"
time="2017-04-28T15:55:40+03:00" level=info msg="generating stub qt/multimedia"
time="2017-04-28T15:55:43+03:00" level=info msg="generating stub qt/quick"
time="2017-04-28T15:55:44+03:00" level=info msg="generating stub qt/help"
time="2017-04-28T15:55:45+03:00" level=info msg="generating stub qt/location"
time="2017-04-28T15:55:45+03:00" level=info msg="generating stub qt/scripttools"
time="2017-04-28T15:55:45+03:00" level=info msg="generating stub qt/uitools"
time="2017-04-28T15:55:45+03:00" level=info msg="generating stub qt/winextras"
time="2017-04-28T15:55:46+03:00" level=info msg="generating stub qt/testlib"
time="2017-04-28T15:55:46+03:00" level=info msg="generating stub qt/serialport"
time="2017-04-28T15:55:46+03:00" level=info msg="generating stub qt/serialbus"
time="2017-04-28T15:55:46+03:00" level=info msg="generating stub qt/printsupport"
time="2017-04-28T15:55:47+03:00" level=info msg="generating stub qt/designer"
time="2017-04-28T15:55:48+03:00" level=info msg="generating stub qt/scxml"
time="2017-04-28T15:55:48+03:00" level=info msg="generating stub qt/gamepad"
time="2017-04-28T15:55:48+03:00" level=info msg="generating stub qt/purchasing"
time="2017-04-28T15:55:48+03:00" level=info msg="generating stub qt/datavisualization"
time="2017-04-28T15:55:49+03:00" level=info msg="generating stub qt/charts"
time="2017-04-28T15:55:50+03:00" level=info msg="generating stub qt/speech"
time="2017-04-28T15:55:50+03:00" level=info msg="generating stub qt/quickcontrols2"
time="2017-04-28T15:55:50+03:00" level=info msg="generating stub qt/sailfish"
time="2017-04-28T15:55:50+03:00" level=info msg="running: 'qtsetup install windows' [docker=false]"
time="2017-04-28T15:55:50+03:00" level=info msg="installing stub qt/core"
time="2017-04-28T15:55:54+03:00" level=info msg="installing stub qt/androidextras"
time="2017-04-28T15:55:55+03:00" level=info msg="installing stub qt/gui"
time="2017-04-28T15:55:59+03:00" level=info msg="installing stub qt/network"
time="2017-04-28T15:56:01+03:00" level=info msg="installing stub qt/xml"
time="2017-04-28T15:56:02+03:00" level=info msg="installing stub qt/dbus"
time="2017-04-28T15:56:03+03:00" level=info msg="installing stub qt/nfc"
time="2017-04-28T15:56:04+03:00" level=info msg="installing stub qt/script"
time="2017-04-28T15:56:05+03:00" level=info msg="installing stub qt/sensors"
time="2017-04-28T15:56:08+03:00" level=info msg="installing stub qt/positioning"
time="2017-04-28T15:56:08+03:00" level=info msg="installing stub qt/widgets"
time="2017-04-28T15:56:33+03:00" level=info msg="installing stub qt/sql"
time="2017-04-28T15:56:35+03:00" level=info msg="installing stub qt/qml"
time="2017-04-28T15:56:36+03:00" level=info msg="installing stub qt/websockets"
time="2017-04-28T15:56:36+03:00" level=info msg="installing stub qt/xmlpatterns"
time="2017-04-28T15:56:37+03:00" level=info msg="installing stub qt/bluetooth"
time="2017-04-28T15:56:38+03:00" level=info msg="installing stub qt/webchannel"
time="2017-04-28T15:56:38+03:00" level=info msg="installing stub qt/svg"
time="2017-04-28T15:56:40+03:00" level=info msg="installing stub qt/multimedia"
time="2017-04-28T15:56:46+03:00" level=info msg="installing stub qt/quick"
time="2017-04-28T15:56:49+03:00" level=info msg="installing stub qt/help"
time="2017-04-28T15:56:52+03:00" level=info msg="installing stub qt/location"
time="2017-04-28T15:56:53+03:00" level=info msg="installing stub qt/scripttools"
time="2017-04-28T15:56:54+03:00" level=info msg="installing stub qt/uitools"
time="2017-04-28T15:56:55+03:00" level=info msg="installing stub qt/winextras"
time="2017-04-28T15:56:56+03:00" level=info msg="installing stub qt/testlib"
time="2017-04-28T15:56:57+03:00" level=info msg="installing stub qt/serialport"
time="2017-04-28T15:56:58+03:00" level=info msg="installing stub qt/serialbus"
time="2017-04-28T15:56:59+03:00" level=info msg="installing stub qt/printsupport"
time="2017-04-28T15:57:01+03:00" level=info msg="installing stub qt/designer"
time="2017-04-28T15:57:03+03:00" level=info msg="installing stub qt/scxml"
time="2017-04-28T15:57:04+03:00" level=info msg="installing stub qt/gamepad"
time="2017-04-28T15:57:05+03:00" level=info msg="installing stub qt/purchasing"
time="2017-04-28T15:57:05+03:00" level=info msg="installing stub qt/datavisualization"
time="2017-04-28T15:57:06+03:00" level=info msg="installing stub qt/charts"
time="2017-04-28T15:57:09+03:00" level=info msg="installing stub qt/speech"
time="2017-04-28T15:57:10+03:00" level=info msg="installing stub qt/quickcontrols2"
time="2017-04-28T15:57:10+03:00" level=info msg="installing stub qt/sailfish"
time="2017-04-28T15:57:11+03:00" level=info msg="running: 'qtsetup test windows' [docker=false]"
time="2017-04-28T15:57:11+03:00" level=info msg="testing qml\application"
time="2017-04-28T15:57:30+03:00" level=error msg="failed to run command" cmd="go build -p 4 -v -ldflags="-s" "-w" "-H=windowsgui" -o C:\Users\ku7ab\Documents\Go\src\github.com\therecipe\qt\internal\examples\qml\application\deploy\windows\application.exe -tags="minimal"" env="GOOS=windows GOROOT=C:\Go\ TEMP=C:\BIN\MSYS2\tmp GOARCH=amd64 CGO_ENABLED=1 PATH=C:\BIN\MSYS2\usr\local\bin;C:\BIN\MSYS2\usr\bin;C:\BIN\MSYS2\usr\bin;C:\BIN\MSYS2\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\BIN\MSYS2\usr\bin\site_perl;C:\BIN\MSYS2\usr\bin\vendor_perl;C:\BIN\MSYS2\usr\bin\core_perl;C:\Go\bin;C:\BIN\MSYS2\mingw64\bin;C:\Users\ku7ab\Documents\Go\bin GOPATH=C:\Users\ku7ab\Documents\Go\ TMP=C:\BIN\MSYS2\tmp" error="exit status 2" func=RunCmd name="build for windows on windows"
github.com/therecipe/qt
runtime/cgo
# runtime/cgo
C:\Go\src\runtime\cgo\gccdump.s:1: expected identifier, found "."
asm: assembly of C:\Go\src\runtime\cgo\gccdump.s failed
```

**Comment by therecipe** [comment] 2017-04-29 22:41
I couldn't reproduce your issue, as it somewhat worked for me.
The compiled binaries weren't statically linked though, but that's fixed now with: https://github.com/therecipe/qt/commit/2274d39b53a49525f5a0dad5b5bab17cb785fc45

I just needed to set:
`PATH=$PATH:/c/Go/bin`
and 
`QT_MSYS2_STATIC=true`

And I used the mingw64 shell, but I didn't explicitly set `QT_MSYS2=true` or `QT_MSYS2_ARCH=amd64` (because it's not really necessary anymore)

Here is my log:

```
$ ./qtsetup.exe
time="2017-04-30T00:26:29+02:00" level=info msg="running: 'qtsetup prep'"
time="2017-04-30T00:26:29+02:00" level=info msg="running: 'qtsetup check windows' [docker=false]"
time="2017-04-30T00:26:29+02:00" level=info msg="GOOS:                        'windows'"
time="2017-04-30T00:26:29+02:00" level=info msg="GOARCH:                      'amd64'"
time="2017-04-30T00:26:29+02:00" level=info msg="GOVERSION:                   'go1.8'"
time="2017-04-30T00:26:29+02:00" level=info msg="GOROOT:                   *  'C:\Go\'"
time="2017-04-30T00:26:29+02:00" level=info msg="GOPATH:                      'C:\Users\user\go'"
time="2017-04-30T00:26:29+02:00" level=info msg="GOBIN:                       'C:\Users\user\go\bin'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_HASH:                     'please install git'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_VERSION:                  '5.8.0'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_VERSION_MAJOR:            '5.8'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_DIR:                      'C:\Qt\Qt5.8.0'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_STUB:                     'true'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_DEBUG:                    'false'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_WEBKIT:                   'false'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_MSYS2:                    'true'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_MSYS2_DIR:                'C:\msys64\mingw64'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_MSYS2_ARCH:               'amd64'"
time="2017-04-30T00:26:29+02:00" level=info msg="QT_MSYS2_STATIC:          *  'true'"
time="2017-04-30T00:26:29+02:00" level=info msg="running: 'qtsetup generate windows' [docker=false]"
time="2017-04-30T00:26:39+02:00" level=info msg="generating stub qt/core"
time="2017-04-30T00:26:42+02:00" level=info msg="generating stub qt/androidextras"
time="2017-04-30T00:26:43+02:00" level=info msg="generating stub qt/gui"
time="2017-04-30T00:26:47+02:00" level=info msg="generating stub qt/network"
time="2017-04-30T00:26:48+02:00" level=info msg="generating stub qt/xml"
time="2017-04-30T00:26:48+02:00" level=info msg="generating stub qt/dbus"
time="2017-04-30T00:26:48+02:00" level=info msg="generating stub qt/nfc"
time="2017-04-30T00:26:48+02:00" level=info msg="generating stub qt/script"
time="2017-04-30T00:26:49+02:00" level=info msg="generating stub qt/sensors"
time="2017-04-30T00:26:49+02:00" level=info msg="generating stub qt/positioning"
time="2017-04-30T00:26:50+02:00" level=info msg="generating stub qt/widgets"
time="2017-04-30T00:26:58+02:00" level=info msg="generating stub qt/sql"
time="2017-04-30T00:26:58+02:00" level=info msg="generating stub qt/qml"
time="2017-04-30T00:26:59+02:00" level=info msg="generating stub qt/websockets"
time="2017-04-30T00:26:59+02:00" level=info msg="generating stub qt/xmlpatterns"
time="2017-04-30T00:26:59+02:00" level=info msg="generating stub qt/bluetooth"
time="2017-04-30T00:27:00+02:00" level=info msg="generating stub qt/webchannel"
time="2017-04-30T00:27:00+02:00" level=info msg="generating stub qt/svg"
time="2017-04-30T00:27:00+02:00" level=info msg="generating stub qt/multimedia"
time="2017-04-30T00:27:02+02:00" level=info msg="generating stub qt/quick"
time="2017-04-30T00:27:03+02:00" level=info msg="generating stub qt/help"
time="2017-04-30T00:27:04+02:00" level=info msg="generating stub qt/location"
time="2017-04-30T00:27:04+02:00" level=info msg="generating stub qt/scripttools"
time="2017-04-30T00:27:04+02:00" level=info msg="generating stub qt/uitools"
time="2017-04-30T00:27:04+02:00" level=info msg="generating stub qt/winextras"
time="2017-04-30T00:27:04+02:00" level=info msg="generating stub qt/testlib"
time="2017-04-30T00:27:05+02:00" level=info msg="generating stub qt/serialport"
time="2017-04-30T00:27:05+02:00" level=info msg="generating stub qt/serialbus"
time="2017-04-30T00:27:05+02:00" level=info msg="generating stub qt/printsupport"
time="2017-04-30T00:27:06+02:00" level=info msg="generating stub qt/designer"
time="2017-04-30T00:27:07+02:00" level=info msg="generating stub qt/scxml"
time="2017-04-30T00:27:07+02:00" level=info msg="generating stub qt/gamepad"
time="2017-04-30T00:27:07+02:00" level=info msg="generating stub qt/purchasing"
time="2017-04-30T00:27:07+02:00" level=info msg="generating stub qt/datavisualization"
time="2017-04-30T00:27:08+02:00" level=info msg="generating stub qt/charts"
time="2017-04-30T00:27:09+02:00" level=info msg="generating stub qt/speech"
time="2017-04-30T00:27:09+02:00" level=info msg="generating stub qt/quickcontrols2"
time="2017-04-30T00:27:09+02:00" level=info msg="generating stub qt/sailfish"
time="2017-04-30T00:27:09+02:00" level=info msg="running: 'qtsetup install windows' [docker=false]"
time="2017-04-30T00:27:09+02:00" level=info msg="installing stub qt/core"
time="2017-04-30T00:27:13+02:00" level=info msg="installing stub qt/androidextras"
time="2017-04-30T00:27:14+02:00" level=info msg="installing stub qt/gui"
time="2017-04-30T00:27:18+02:00" level=info msg="installing stub qt/network"
time="2017-04-30T00:27:20+02:00" level=info msg="installing stub qt/xml"
time="2017-04-30T00:27:21+02:00" level=info msg="installing stub qt/dbus"
time="2017-04-30T00:27:21+02:00" level=info msg="installing stub qt/nfc"
time="2017-04-30T00:27:22+02:00" level=info msg="installing stub qt/script"
time="2017-04-30T00:27:22+02:00" level=info msg="installing stub qt/sensors"
time="2017-04-30T00:27:25+02:00" level=info msg="installing stub qt/positioning"
time="2017-04-30T00:27:25+02:00" level=info msg="installing stub qt/widgets"
time="2017-04-30T00:27:46+02:00" level=info msg="installing stub qt/sql"
time="2017-04-30T00:27:48+02:00" level=info msg="installing stub qt/qml"
time="2017-04-30T00:27:49+02:00" level=info msg="installing stub qt/websockets"
time="2017-04-30T00:27:49+02:00" level=info msg="installing stub qt/xmlpatterns"
time="2017-04-30T00:27:50+02:00" level=info msg="installing stub qt/bluetooth"
time="2017-04-30T00:27:51+02:00" level=info msg="installing stub qt/webchannel"
time="2017-04-30T00:27:51+02:00" level=info msg="installing stub qt/svg"
time="2017-04-30T00:27:52+02:00" level=info msg="installing stub qt/multimedia"
time="2017-04-30T00:27:57+02:00" level=info msg="installing stub qt/quick"
time="2017-04-30T00:27:59+02:00" level=info msg="installing stub qt/help"
time="2017-04-30T00:28:01+02:00" level=info msg="installing stub qt/location"
time="2017-04-30T00:28:02+02:00" level=info msg="installing stub qt/scripttools"
time="2017-04-30T00:28:03+02:00" level=info msg="installing stub qt/uitools"
time="2017-04-30T00:28:04+02:00" level=info msg="installing stub qt/winextras"
time="2017-04-30T00:28:05+02:00" level=info msg="installing stub qt/testlib"
time="2017-04-30T00:28:06+02:00" level=info msg="installing stub qt/serialport"
time="2017-04-30T00:28:06+02:00" level=info msg="installing stub qt/serialbus"
time="2017-04-30T00:28:07+02:00" level=info msg="installing stub qt/printsupport"
time="2017-04-30T00:28:08+02:00" level=info msg="installing stub qt/designer"
time="2017-04-30T00:28:10+02:00" level=info msg="installing stub qt/scxml"
time="2017-04-30T00:28:11+02:00" level=info msg="installing stub qt/gamepad"
time="2017-04-30T00:28:11+02:00" level=info msg="installing stub qt/purchasing"
time="2017-04-30T00:28:12+02:00" level=info msg="installing stub qt/datavisualization"
time="2017-04-30T00:28:13+02:00" level=info msg="installing stub qt/charts"
time="2017-04-30T00:28:15+02:00" level=info msg="installing stub qt/speech"
time="2017-04-30T00:28:16+02:00" level=info msg="installing stub qt/quickcontrols2"
time="2017-04-30T00:28:16+02:00" level=info msg="installing stub qt/sailfish"
time="2017-04-30T00:28:17+02:00" level=info msg="running: 'qtsetup test windows' [docker=false]"
time="2017-04-30T00:28:17+02:00" level=info msg="testing quick\calc"
time="2017-04-30T00:29:52+02:00" level=info msg="testing widgets\line_edits"
time="2017-04-30T00:31:14+02:00" level=info msg="testing widgets\pixel_editor"
time="2017-04-30T00:32:37+02:00" level=info msg="testing widgets\textedit"
time="2017-04-30T00:34:53+02:00" level=info msg="testing qml\application"
time="2017-04-30T00:36:08+02:00" level=info msg="testing qml\drawer_nav_x"
```

and the packages I installed with `pacman -S mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt5-static`:

```
$ pacman -Q
bash 4.4.012-1
bash-completion 2.3-1
bsdcpio 3.2.1-1
bsdtar 3.2.1-1
bzip2 1.0.6-2
ca-certificates 20150426-1
catgets 1.1-2
coreutils 8.25-1
crypt 1.3-1
curl 7.50.3-1
dash 0.5.9.1-1
file 5.28-2
filesystem 2017.02-4
findutils 4.6.0-1
flex 2.6.1-1
gawk 4.1.4-1
gcc-libs 5.3.0-3
gettext 0.19.7-3
gmp 6.1.0-2
gnupg 1.4.20-1
grep 2.26-1
gzip 1.8-1
heimdal-libs 1.5.3-9
icu 56.1-1
inetutils 1.9.2-1
info 6.1-1
less 481-1
libarchive 3.2.1-1
libasprintf 0.19.7-3
libassuan 2.4.2-1
libbz2 1.0.6-2
libcatgets 1.1-2
libcrypt 1.3-1
libcurl 7.50.3-1
libdb 5.3.28-2
libedit 3.1-20150325
libexpat 2.2.0-1
libffi 3.2.1-1
libgettextpo 0.19.7-3
libgpg-error 1.23-1
libgpgme 1.6.0-1
libiconv 1.14-2
libidn 1.33-1
libintl 0.19.7-3
liblzma 5.2.2-1
liblzo2 2.09-1
libmetalink 0.1.2-2
libnettle 3.3-1
libopenssl 1.0.2.j-1
libp11-kit 0.23.2-1
libpcre 8.38-1
libpcre16 8.38-1
libpcre32 8.38-1
libpcrecpp 8.38-1
libpcreposix 8.38-1
libreadline 6.3.008-7
libsqlite 3.10.0.0-1
libssh2 1.7.0-1
libtasn1 4.9-1
libutil-linux 2.26.2-1
libxml2 2.9.2-2
lndir 1.0.3-1
m4 1.4.17-4
mingw-w64-x86_64-assimp 3.3.1-1
mingw-w64-x86_64-binutils 2.28-1
mingw-w64-x86_64-bzip2 1.0.6-6
mingw-w64-x86_64-ca-certificates 20170211-2
mingw-w64-x86_64-cairo 1.15.4-4
mingw-w64-x86_64-crt-git 5.0.0.4817.b0e7567e-1
mingw-w64-x86_64-dbus 1.10.16-1
mingw-w64-x86_64-expat 2.2.0-2
mingw-w64-x86_64-fontconfig 2.12.1-1
mingw-w64-x86_64-freeglut 3.0.0-4
mingw-w64-x86_64-freetype 2.7.1-1
mingw-w64-x86_64-gcc 6.3.0-2
mingw-w64-x86_64-gcc-libs 6.3.0-2
mingw-w64-x86_64-gettext 0.19.8.1-2
mingw-w64-x86_64-giflib 5.1.4-1
mingw-w64-x86_64-glib2 2.52.0-1
mingw-w64-x86_64-gmp 6.1.2-1
mingw-w64-x86_64-graphite2 1.3.9-1
mingw-w64-x86_64-harfbuzz 1.4.5-1
mingw-w64-x86_64-headers-git 5.0.0.4819.e4dfb654-1
mingw-w64-x86_64-icu 57.1-2
mingw-w64-x86_64-icu-debug-libs 57.1-2
mingw-w64-x86_64-isl 0.17.1-1
mingw-w64-x86_64-jasper 2.0.12-1
mingw-w64-x86_64-lcms2 2.8-1
mingw-w64-x86_64-libffi 3.2.1-4
mingw-w64-x86_64-libgcrypt 1.7.6-1
mingw-w64-x86_64-libgpg-error 1.25-1
mingw-w64-x86_64-libiconv 1.15-1
mingw-w64-x86_64-libjpeg-turbo 1.5.1-1
mingw-w64-x86_64-libmng 2.0.3-3
mingw-w64-x86_64-libpng 1.6.29-1
mingw-w64-x86_64-libsystre 1.0.1-3
mingw-w64-x86_64-libtasn1 4.9-1
mingw-w64-x86_64-libtiff 4.0.7-2
mingw-w64-x86_64-libtre-git r128.6fb7206-1
mingw-w64-x86_64-libwebp 0.6.0-1
mingw-w64-x86_64-libwinpthread-git 5.0.0.4816.8692be6a-1
mingw-w64-x86_64-libxml2 2.9.4-4
mingw-w64-x86_64-libxslt 1.1.29-3
mingw-w64-x86_64-lzo2 2.10-1
mingw-w64-x86_64-make 4.2.1-1
mingw-w64-x86_64-mpc 1.0.3-2
mingw-w64-x86_64-mpfr 3.1.5.p1-1
mingw-w64-x86_64-ncurses 6.0.20170325-1
mingw-w64-x86_64-openssl 1.0.2.k-1
mingw-w64-x86_64-p11-kit 0.23.5-1
mingw-w64-x86_64-pcre 8.40-1
mingw-w64-x86_64-pixman 0.34.0-3
mingw-w64-x86_64-qbs 1.7.1-1
mingw-w64-x86_64-qt-creator 4.2.1-2
mingw-w64-x86_64-qt5 5.8.0-3
mingw-w64-x86_64-qt5-static 5.8.0-1
mingw-w64-x86_64-qtbinpatcher 2.2.0-1
mingw-w64-x86_64-readline 7.0.003-1
mingw-w64-x86_64-sqlite3 3.18.0-1
mingw-w64-x86_64-termcap 1.3.1-2
mingw-w64-x86_64-windows-default-manifest 6.4-3
mingw-w64-x86_64-wineditline 2.201-1
mingw-w64-x86_64-winpthreads-git 5.0.0.4816.8692be6a-1
mingw-w64-x86_64-xpm-nox 4.2.0-4
mingw-w64-x86_64-xz 5.2.3-1
mingw-w64-x86_64-zlib 1.2.11-1
mingw-w64-x86_64-zziplib 0.13.62-5
mintty 1~2.7.3-1
mpfr 3.1.4-1
msys2-keyring r9.397a52e-1
msys2-launcher-git 0.3.32.56c2ba7-2
msys2-runtime 2.7.0-1
ncurses 6.0.20161001-1
openssl 1.0.2.j-1
p11-kit 0.23.2-1
pacman 5.0.1-2
pacman-mirrors 20160112-1
pactoys-git r2.07ca37f-1
pax-git 20140703.2.1.g469552a-1
pcre 8.38-1
pkgfile 15-1
rebase 4.4.2-1
sed 4.2.2-2
tftp-hpa 5.2-1
time 1.7-1
ttyrec 1.0.8-1
tzcode 2015.e-1
util-linux 2.26.2-1
wget 1.18-1
which 2.21-2
xz 5.2.2-1
zlib 1.2.8-3
```

Could you try it again with the new version?

**Comment by Kutabe** [comment] 2017-04-30 00:18
Well, it took some time, but I figured out what went wrong and I think it can be fixed somehow.
So, I updated `therecipe/qt` and checked all the packages, tried to build it and oops, same error. 
I googled `asm: assembly of C:\Go\src\runtime\cgo\gccdump.s failed` and found nothing. 
Then I googled `src\runtime\cgo\gccdump.s` and again, found nothing.
So I deleted my Go compiler and set of tools, but some of files left in `C:\Go`. I removed it manually, reinstalled Go and yep, it worked. And it seems it doesn't auto-detect `QT_MSYS2_ARCH`, maybe because my path is specific (`C:\BIN\MSYS2`) or because I run MSYS2 shell (`msys2.exe`), not `mingw64.exe.`
I don't know where this files came from though. Maybe I messed it up somehow. Issue closed, I think.

**Closed** 2017-04-30 21:13 UTC

**Comment by therecipe** [comment] 2017-04-30 22:25
Ah, great to hear that it works now :)

>I removed it manually, reinstalled Go and yep, it worked.

Yeah, had to do that myself a few times as well.

> And it seems it doesn't auto-detect QT_MSYS2_ARCH, maybe because my path is specific (C:\BIN\MSYS2) or because I run MSYS2 shell (msys2.exe), not mingw64.exe.

Yes, sorry if you use msys2 and not one of the two shells, then you probably need to explicitly set both env variables.
