### ISSUE TITLE
Hitting infinite loop in moc.go

### ISSUE THREAD

**Issue by yshurik** [therecipe/qt#676] opened 2018-07-25 19:40 UTC
Looks my project gets into infinite loop with qtdeploy at:

"start copy structors"

https://github.com/therecipe/qt/blob/master/internal/cmd/moc/moc.go#L263
https://github.com/therecipe/qt/blob/master/internal/cmd/moc/moc.go#L268

Symptoms - never ending after debug message "start copy structors".

If just add some debug print inside like: 

fmt.Println(c.Bases)

Then chance of infinite loop can reduce to approx 50%, so probably also race condition obstacle/bug?
(but if hit again, it just keep printing never ending)

**Comment by therecipe** [comment] 2018-08-05 17:10
Hey

I will look into this, but could you maybe try to reproduce the issue with ` qtmoc -slow`?
The "slow" flag should limit the whole qtmoc process to only one go routine, so we can rule out race conditions and such.

Also is it possible that you post some code so I can easily reproduce the issue?
I guess the issue is probably related to the names of your structs, do you have multiple structs with the same name or something?
Or do you subclass already subclassed classes?

**Comment by skaldesh** [comment] 2018-10-06 20:03
maybe same issue as mentioned in #701 ? 
@yshurik can you please provide your code?

**Comment by therecipe** [comment] 2019-05-08 19:28
I will close this now, since it seems to be a duplicate of #701, which was fixed some time ago.

**Closed by therecipe** 2019-05-08 19:28 UTC

**Comment by logrusorgru** [comment] 2019-05-20 08:46
It is stuck on the `"start copy structors"` if structure name is the same as signal name. For example

```go
type inMainThread struct {
    core.QObject

    _ func(func()) `signal:"inMainThread,auto"`
}
```
But it is ok if

```go
type mainThread struct {
    core.QObject

    _ func(func()) `signal:"inMainThread,auto"`
}
```

**Comment by yshurik** [comment] 2019-05-20 10:10
good catch

**Comment by therecipe** [comment] 2019-05-21 22:28
@logrusorgru Thanks, this should fixed now with https://github.com/therecipe/qt/commit/8a927e9edb1f007b14c790445ec15a9c405bff83

The problem was that you usually can't name a method the same as an struct because the struct name is reserved for the c++ constructor. But I worked around this, because the name is still available in Go land.
