### ISSUE TITLE
Window executable error

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#595] opened 2018-04-14 09:37 UTC
Hi,

I tried to build my app on windows using {{go build}} but got error mentioning `Qt5Core.dll` is missing, screenshot attached. Please try to build my sample repo: https://github.com/arknable/therecipe-issue-support.git ... you'll see same result. Do I probably missing a setup or something ? 

![screen shot 2018-04-14 at 4 24 07 pm](https://user-images.githubusercontent.com/13412168/38766823-001aabcc-4002-11e8-8e96-2013e50f2f71.png)

Thanks.

**Comment by arknable** [comment] 2018-04-14 09:39
oh I forgot to mention, if I used `qtdeploy` it works fine. I assume this is just about dll inclusion or something during build .. probably.

**Comment by therecipe** [comment] 2018-04-16 17:41
Hey

Yeah, on windows you will need to use `qtdeploy` at least once to copy the `*.dll` files inside the `deploy/windows` folder. The problem is that there is no `rpath` like feature on linux/macOS afaik, and the only options to emulate something like it are some hacky.
So just use `qtdeploy` and then `qtdeploy -fast ...` (or `go build -o `deploy/windows/` in the meantime.
But please leave this open, I will look into this again.

**Comment by arknable** [comment] 2018-04-17 21:36
Hey,
I tried `qtdeploy -fast` and `go build`, but I got following error. I can fixed it by copying `Qt5QuickWidgets.dll` to deployment folder. 

![build_err](https://user-images.githubusercontent.com/13412168/38899113-21c6e0f8-42c1-11e8-8538-40f2f157ca4d.PNG)

**Comment by therecipe** [comment] 2019-01-03 18:13
Will close this, since it is possible now to use `qtdeploy -fast` without running the "full" `qtdeploy` first.

**Closed by therecipe** 2019-01-03 18:13 UTC
