### ISSUE TITLE
How to properly call QMetaObject::InvokeMethod?

### ISSUE THREAD

**Issue by hanbang-wang** [therecipe/qt#390] opened 2017-07-02 16:49 UTC
Since it was not possible to draw gui in worker thread, I was trying to call a slot to achieve the same effect. 
```Go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	c := widgets.NewQPushButton2("Test", nil)
	c.ConnectClicked(func(bool) {
		c.SetDisabled(true)
		suc := widgets.NewQMessageBox(nil)
		go func() {
			time.Sleep(1 * time.Second)
			suc.SetText("Success!")
			c.SetEnabled(true)
			core.QMetaObject_InvokeMethod3(suc, "exec", core.Qt__BlockingQueuedConnection, core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil), core.NewQGenericArgumentFromPointer(nil))
		}()
	})
	window := widgets.NewQMainWindow(nil, core.Qt__Widget)
	window.SetCentralWidget(c)
	window.Show()
	widgets.QApplication_Exec()
}
```
However, this code will panic at `core.QMetaObject_InvokeMethod3`. So how to properly use this function?

**Comment by hanbang-wang** [comment] 2017-07-03 11:23
After many searching, I finally realize that only the main-thread can do graphical output, thx.

**Comment by therecipe** [comment] 2017-07-04 21:49
Hey

Yeah, unfortunately is not possible to directly use `QMetaObject_InvokeMethod` or `core.NewQGenericArgument` at the moment.

You will instead need to create a helper struct with a custom signal/slot to be able to make all the visual changes in the main thread. (The signal/slots are always called with: `Qt::AutoConnection`)

So something like this should work:

```go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

type MessageBox struct {
	widgets.QMessageBox

	_ func() `constructor:"init"`

	//_ func(t string, c *widgets.QPushButton) `slot:"customExec"` //should work once the bug is fixed
	_ func(t string, c *core.QObject) `slot:"customExec"`
}

func (mb *MessageBox) init() {
	mb.ConnectCustomExec(func(t string, co *core.QObject) {
		c := widgets.NewQPushButtonFromPointer(co.Pointer()) //shouldn't be needed later
		mb.SetText(t)
		c.SetEnabled(true)
		println(mb.Exec())
	})
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	c := widgets.NewQPushButton2("Test", nil)
	c.ConnectClicked(func(bool) {
		c.SetDisabled(true)
		suc := NewMessageBox(nil)
		go func() {
			time.Sleep(1 * time.Second)
			suc.CustomExec("Success!", c)
		}()
	})
	window := widgets.NewQMainWindow(nil, core.Qt__Widget)
	window.SetCentralWidget(c)
	window.Show()
	widgets.QApplication_Exec()
}
```

Usually you should be also able to use
```
_ func(t string, c *widgets.QPushButton) `slot:"customExec"`
```
instead of 
```
_ func(t string, c *core.QObject) `slot:"customExec"`
```

but there seems to be a bug,  so I will need to look into this first.

**Comment by hanbang-wang** [comment] 2017-07-07 09:16
A little modification makes it neither display nor print anything.
```Go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

type MessageBox struct {
	widgets.QMessageBox

	_ func() `constructor:"init"`

	_ func(string, widgets.QMessageBox__Icon, *core.QObject) `slot:"customExec"`
}

func (mb *MessageBox) init() {
	mb.ConnectCustomExec(func(t string, icon widgets.QMessageBox__Icon, co *core.QObject) {
		c := widgets.NewQPushButtonFromPointer(co.Pointer()) //shouldn't be needed later
		mb.SetText(t)
		mb.SetIcon(icon)
		c.SetEnabled(true)
		println(mb.Exec())
	})
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	c := widgets.NewQPushButton2("Test", nil)
	c.ConnectClicked(func(bool) {
		c.SetDisabled(true)
		suc := NewMessageBox(nil)
		go func() {
			time.Sleep(1 * time.Second)
			suc.CustomExec("Success!", widgets.QMessageBox__Information, c)
		}()
	})
	window := widgets.NewQMainWindow(nil, core.Qt__Widget)
	window.SetCentralWidget(c)
	window.Show()
	widgets.QApplication_Exec()
}
```

**Comment by therecipe** [comment] 2017-07-11 21:49
Sorry it took a little longer, but both issues should be fixed now with: https://github.com/therecipe/qt/commit/0f99eb634c8837bffcd4fd524ec8169692042d41
The "QObject*" one was a regression, and the new one was due the unregistered enums.

This should work now:
```go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/widgets"
)

type MessageBox struct {
	widgets.QMessageBox

	_ func() `constructor:"init"`

	_ func(string, widgets.QMessageBox__Icon, *widgets.QPushButton) `slot:"customExec"`
}

func (mb *MessageBox) init() {
	mb.ConnectCustomExec(func(t string, icon widgets.QMessageBox__Icon, c *widgets.QPushButton) {
		mb.SetText(t)
		mb.SetIcon(icon)
		c.SetEnabled(true)
		println(mb.Exec())
	})
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	c := widgets.NewQPushButton2("Test", nil)
	c.ConnectClicked(func(bool) {
		c.SetDisabled(true)
		suc := NewMessageBox(nil)
		go func() {
			time.Sleep(1 * time.Second)
			suc.CustomExec("Success!", widgets.QMessageBox__Information, c)
		}()
	})
	window := widgets.NewQMainWindow(nil, core.Qt__Widget)
	window.SetCentralWidget(c)
	window.Show()
	widgets.QApplication_Exec()
}
```

**Comment by hanbang-wang** [comment] 2017-07-12 10:59
That works, thanks!

_Sent from my Samsung SM-G9500 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-07-12 11:00 UTC
