### ISSUE TITLE
Thank you! It works well.

### ISSUE THREAD

**Issue by kybin** [therecipe/qt#1] opened 2014-11-27 06:02 UTC
Hi, therecipe. Thank you for this hard work.
I ran the example. And it works well without any error in my opensuse13.2!

**Comment by sunwangme** [comment] 2015-08-15 07:53
wonderful! how to gen the bindings? swig?

**Comment by xi2** [comment] 2015-08-25 02:00
Hi therecipe. This looks to be excellent work. Like @sunwangme I am also curious to know about the bindings generator. Will you be releasing it, or at least detailing it? I'm fine with you choosing not to, but it would be nice to know if it's coming or not before I choose to use these bindings for something non-trivial. Best wishes and thanks once again for your contribution.

**Comment by therecipe** [comment] 2015-09-06 19:46
Hey

I currently got no access to the files, but I will try to release them in the next 1-2 weeks.
After I got some time to update the code and get it to work with qt 5.5 and go 1.5.

Also, I'm happy that you find this binding useful and I would love to see something build with it :)

**Comment by xi2** [comment] 2015-09-06 20:06
Hi. Thanks for replying. I'm not sure I'm going to be using your bindings yet since I'm undecided at the moment about the best approach to GUI using Go and still exploring the available options, but it will be interesting to see how you develop them in the future. Best wishes.

**Comment by sunwangme** [comment] 2015-09-07 05:17
Best wishes.

**Comment by therecipe** [comment] 2015-09-24 13:00
Hey
I will release the files asap.
But it takes a bit longer, because I also want to get it running on android.

**Comment by sunwangme** [comment] 2015-09-24 14:18
thanks

**Comment by therecipe** [comment] 2015-10-24 15:45
Hey
It took me longer than I expected, but here it is.
I rewrote the generator and got most qt modules working.

However, the generator code is still messy and the generated code is working, but could be better.

I got a long todo list and will work on it in the following weeks.

The next major points I will work on, are to get it working on windows.
(There is a problem with how g++ is invoking the "collect2.exe" -> https://support.microsoft.com/kb/830473)

And to get a decend deployment mechanism for android, currently I got it working by injecting the generated go library from gomobile in a modefied qt apk.

Please report any issues you may encounter.

**Comment by sunwangme** [comment] 2015-10-24 18:47
thanks

**Comment by sunwangme** [comment] 2015-10-25 00:59
how to get https://github.com/therecipe/qt/tree/master/internal/binding/dump?

**Comment by therecipe** [comment] 2015-10-25 14:27
You can run the https://github.com/therecipe/qt/internal/binding/make.sh or .bat

**Comment by sunwangme** [comment] 2015-10-25 14:47
haha, theory: gen from doc.index

thanks

**Comment by therecipe** [comment] 2015-11-09 17:43
Hey

I just pushed the new files.
You are now able to create android apks from mac and linux with `qtdeploy`.
And the next thing on my todo list is to get it working under windows.

**Comment by sunwangme** [comment] 2015-11-10 02:26
thanks for your hard work!

**Comment by xland** [comment] 2015-11-10 02:50
@therecipe 

"(windows is currently not working) -> https://support.microsoft.com/kb/830473"

Is this mean this project can not run exactly on windows

**Comment by therecipe** [comment] 2015-11-10 14:33
The problem is that "go install" invokes "g++" in the following way:
"g++ path/to/file1.o path/to/file2.o path/to/file3.o ... path/to/file1500.o" which results in an very long command-line string.
Thats no problem under linux or mac, but windows can't handle this.

So, I will have to:
a) Provide a modded "go install" version which uses "response files"
b) Fill out a bug report
c) Rewrite the "setup/install.go" code, so that it continues the install process after "go install" failed

But after that, the binding should work on windows.

**Comment by xland** [comment] 2015-11-11 01:16
OK~
I'll wait for this

**Comment by therecipe** [comment] 2015-11-11 18:54
Okay, I got it working.
The cpp files are now combined in one big file for each sub-package/module, which solves the problem.

I will push the files in the next few hours, when I got the android deployment working on windows also.

**Comment by therecipe** [comment] 2015-11-12 00:39
So, I pushed the changes.
It's now also working on windows.

From now, I will focus on cleaning up the code.

**Comment by xland** [comment] 2015-11-12 03:31
@therecipe 

Thank you very much!

**Comment by jonywtf** [comment] 2015-11-28 08:31
@therecipe, Thanks!
my "custom build" hello, world! on windows:
https://github.com/jonywtf/goqt_hello_world

**Closed** 2016-01-18 14:32 UTC
