### ISSUE TITLE
tried to setup for kindle failed.

### ISSUE THREAD

**Issue by idalin** [therecipe/qt#862] opened 2019-05-16 06:18 UTC
Hi, i am trying to build for my kindle paperwhite, but failed.
here is my env:
```bash
export GOARCH=arm
export GOOS=linux
export CGO_ENABLED=1
export GOROOT=/usr/local/go
export GOPATH=/home/dalin/go
export PATH=$GOROOT/bin:/home/dalin/go/bin:$PATH
export SYSROOT=/home/dalin/opt/cross-gcc-linaro/arm-linux-gnueabi
export CC=/home/dalin/opt/cross-gcc-linaro/bin/arm-linux-gnueabi-gcc
export CXX=/home/dalin/opt/cross-gcc-linaro/bin/arm-linux-gnueabi-g++
export QT_API=5.9.0
export QT_VERSION=5.9.3
export QT_INC="-I/opt/kindle-qt5/target/include/QtAccessibilitySupport -I/opt/kindle-qt5/target/include/QtConcurrent -I/opt/kindle-qt5/target/include/QtCore -I/opt/kindle-qt5/target/include/QtDBus -I/opt/kindle-qt5/target/include/QtDeviceDiscoverySupport -I/opt/kindle-qt5/target/include/QtEventDispatcherSupport -I/opt/kindle-qt5/target/include/QtFbSupport -I/opt/kindle-qt5/target/include/QtFontDatabaseSupport -I/opt/kindle-qt5/target/include/QtGlxSupport -I/opt/kindle-qt5/target/include/QtGui -I/opt/kindle-qt5/target/include/QtHelp -I/opt/kindle-qt5/target/include/QtInputSupport -I/opt/kindle-qt5/target/include/QtNetwork -I/opt/kindle-qt5/target/include/QtOpenGL -I/opt/kindle-qt5/target/include/QtOpenGLExtensions -I/opt/kindle-qt5/target/include/QtPacketProtocol -I/opt/kindle-qt5/target/include/QtPlatformCompositorSupport -I/opt/kindle-qt5/target/include/QtPlatformHeaders -I/opt/kindle-qt5/target/include/QtPrintSupport -I/opt/kindle-qt5/target/include/QtQml -I/opt/kindle-qt5/target/include/QtQmlDebug -I/opt/kindle-qt5/target/include/QtQuick -I/opt/kindle-qt5/target/include/QtQuickControls2 -I/opt/kindle-qt5/target/include/QtQuickParticles -I/opt/kindle-qt5/target/include/QtQuickTemplates2 -I/opt/kindle-qt5/target/include/QtQuickTest -I/opt/kindle-qt5/target/include/QtQuickWidgets -I/opt/kindle-qt5/target/include/QtRemoteObjects -I/opt/kindle-qt5/target/include/QtRepParser -I/opt/kindle-qt5/target/include/QtScript -I/opt/kindle-qt5/target/include/QtScriptTools -I/opt/kindle-qt5/target/include/QtServiceSupport -I/opt/kindle-qt5/target/include/QtSql -I/opt/kindle-qt5/target/include/QtTest -I/opt/kindle-qt5/target/include/QtThemeSupport -I/opt/kindle-qt5/target/include/QtUiPlugin -I/opt/kindle-qt5/target/include/QtUiTools -I/opt/kindle-qt5/target/include/QtWebChannel -I/opt/kindle-qt5/target/include/QtWidgets -I/opt/kindle-qt5/target/include/QtX11Extras -I/opt/kindle-qt5/target/include/QtXml -I/opt/kindle-qt5/target/include/QtXmlPatterns -I/opt/kindle-qt5/target/include/QtZlib"
export QT_QMAKE_DIR=/opt/kindle-qt5/host/bin
export QT_DIR=/opt/kindle-qt5/host/target
export CGO_CFLAGS="-g -O2 -I/opt/kindle-qt5/target/include $QT_INC -L/home/dalin/opt/lib -L/home/dalin/opt/cross-gcc-linaro/arm-linux-gnueabi/lib -L/opt/kindle-qt5/target/lib --sysroot $SYSROOT"
export CGO_CXXFLAGS="-g -O2 -I/opt/kindle-qt5/target/include $QT_INC -L/home/dalin/opt/lib -L/home/dalin/opt/cross-gcc-linaro/arm-linux-gnueabi/lib -L/opt/kindle-qt5/target/lib --sysroot $SYSROOT -std=c++11"
export CGO_LDFLAGS="-g -O2 -I/opt/kindle-qt5/target/include $QT_INC -L/home/dalin/opt/lib -L/home/dalin/opt/cross-gcc-linaro/arm-linux-gnueabi/lib -L/opt/kindle-qt5/target/lib --sysroot $SYSROOT"
```
`/home/dalin/opt/cross-gcc-linaro/` is my kindle toolchain.  `/opt/kindle-qt5` is Qt 5.9.3 built for kindle (downloaded from here: https://drive.google.com/file/d/1BS2FycusEQv70E9llHmsxKmQaTSdroVA/view ). `/home/dalin/opt/lib` is a copy of kindle's /usr/lib.

```
➜  ~ qtsetup -qt_dir=/opt/kindle-qt5/target
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/sbin/qtrcc); please use /home/dalin/go/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/sbin/qtmoc); please use /home/dalin/go/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/sbin/qtminimal); please use /home/dalin/go/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/sbin/qtdeploy); please use /home/dalin/go/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                     *  'linux'         
INFO[0000] GOARCH:                   *  'arm'           
INFO[0000] GOVERSION:                   'go1.12.5'      
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/dalin/go' 
INFO[0000] GOBIN:                       '/home/dalin/go/bin' 
INFO[0000] GOMOD:                       ''              
INFO[0000] QT_HASH:                     '89b7941f483a7a450aa72057326d3401aca58cfe' 
INFO[0000] QT_API:                   *  '5.9.0'         
INFO[0000] QT_VERSION:               *  '5.9.3'         
INFO[0000] QT_DIR:                   *  '/opt/kindle-qt5/target' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:             *  '/opt/kindle-qt5/host/bin' 
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
INFO[0002] generating full qt/core                      
INFO[0009] generating full qt/androidextras             
INFO[0009] generating full qt/gui
...
...
INFO[0076] generating full qt/quickcontrols2            
INFO[0076] generating full qt/sailfish                  
INFO[0076] generating full qt/webview                   
INFO[0076] generating full qt/remoteobjects             
INFO[0076] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0076] installing full qt/core 
```
and than failed with:
```
...
...
...
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV15MyQStateMachine[_ZTV15MyQStateMachine]+0x48): undefined reference to `QStateMachine::beginMicrostep(QEvent*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV15MyQStateMachine[_ZTV15MyQStateMachine]+0x4c): undefined reference to `QStateMachine::endMicrostep(QEvent*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV18MyQStringListModel[_ZTV18MyQStringListModel]+0xc): undefined reference to `QStringListModel::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV18MyQStringListModel[_ZTV18MyQStringListModel]+0x10): undefined reference to `QStringListModel::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV16MyQTemporaryFile[_ZTV16MyQTemporaryFile]+0xc): undefined reference to `QTemporaryFile::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV16MyQTemporaryFile[_ZTV16MyQTemporaryFile]+0x10): undefined reference to `QTemporaryFile::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV16MyQTemporaryFile[_ZTV16MyQTemporaryFile]+0x3c): undefined reference to `QTemporaryFile::open(QFlags<QIODevice::OpenModeFlag>)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV9MyQThread[_ZTV9MyQThread]+0xc): undefined reference to `QThread::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV9MyQThread[_ZTV9MyQThread]+0x10): undefined reference to `QThread::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV13MyQThreadPool[_ZTV13MyQThreadPool]+0xc): undefined reference to `QThreadPool::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV13MyQThreadPool[_ZTV13MyQThreadPool]+0x10): undefined reference to `QThreadPool::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV11MyQTimeLine[_ZTV11MyQTimeLine]+0xc): undefined reference to `QTimeLine::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV11MyQTimeLine[_ZTV11MyQTimeLine]+0x10): undefined reference to `QTimeLine::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV8MyQTimer[_ZTV8MyQTimer]+0xc): undefined reference to `QTimer::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV8MyQTimer[_ZTV8MyQTimer]+0x10): undefined reference to `QTimer::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV13MyQTranslator[_ZTV13MyQTranslator]+0xc): undefined reference to `QTranslator::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV13MyQTranslator[_ZTV13MyQTranslator]+0x10): undefined reference to `QTranslator::qt_metacall(QMetaObject::Call, int, void**)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV19MyQVariantAnimation[_ZTV19MyQVariantAnimation]+0xc): undefined reference to `QVariantAnimation::qt_metacast(char const*)'
/tmp/go-build369244932/b001/_x004.o:(.data.rel.ro._ZTV19MyQVariantAnimation[_ZTV19MyQVariantAnimation]+0x10): undefined reference to `QVariantAnimation::qt_metacall(QMetaObject::Call, int, void**)'
collect2: error: ld returned 1 exit status

ERRO[0110] failed to install 'core'; aborting setup   
```
thanks for any help.

**Comment by therecipe** [comment] 2019-05-16 17:14
Hey

Can you try to run `qtsetup test`?
Installing the modules is not really necessary to get this working, because qtdeploy/qtminimal will generate and compile a subset of the binding.
And it might work as long as you don't make use of the `*::qt_metacast` and `*:: qt_metacall ` functions. (and the few other functions that can't be found)

If this won't work, then maybe try to make this change:
```diff
diff --git a/internal/binding/templater/template_cgo_qmake.go b/internal/binding/templater/template_cgo_qmake.go
index 5b9e546b..7e4b91f2 100644
--- a/internal/binding/templater/template_cgo_qmake.go
+++ b/internal/binding/templater/template_cgo_qmake.go
@@ -285,7 +285,7 @@ func createMakefile(module, path, target string, mode int) {
                }
                cmd.Args = append(cmd.Args, []string{"-spec", "win32-g++", "CONFIG+=" + subsystem}...)
        case "linux":
-               cmd.Args = append(cmd.Args, []string{"-spec", "linux-g++"}...)
+               cmd.Args = append(cmd.Args, []string{"-spec", "linux-arm-gnueabi-g++"}...)
        case "ios":
                cmd.Args = append(cmd.Args, []string{"-spec", "macx-ios-clang", "CONFIG+=iphoneos", "CONFIG+=device"}...)
        case "ios-simulator":
```
and test it again.


Also btw, did you compile the toolchain on your own by using some source of https://www.amazon.com/gp/help/customer/display.html?nodeId=200203720?
Or did you use https://github.com/samsheff/Amazon-Kindle-Cross-Toolchain, 
or some other prebuilt version from linaro?
I tried to reproduce it and maybe create a docker image, but I wasn't sure which toolchain I should use.

**Comment by idalin** [comment] 2019-05-17 01:32
thanks for your reply.
I compiled the toolchain on my own by using this source https://kindle.s3.amazonaws.com/Kindle_src_5.8.1_2974910023.tar.gz.

and failed again. I found some error in debug log:
```
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QLightSensor module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QMagnetometer module=Sensors      
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QMagnetometerFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QMagnetometerReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QOrientationFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QOrientationReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QOrientationSensor module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QPressureFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QPressureReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QPressureSensor module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QProximityFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QProximityReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QProximitySensor module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QRotationFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QRotationReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QRotationSensor module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensor module=Sensors       
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorBackend module=Sensors       
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorBackendFactory module=Sensors  
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorChangesInterface module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorGesture module=Sensors       
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorGestureManager module=Sensors        
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorGesturePluginInterface module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorGestureRecognizer module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorManager module=Sensors        
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorPluginInterface module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QSensorReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QTapFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QTapReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QTapSensor module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QTiltFilter module=Sensors 
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QTiltReading module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QTiltSensor module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QtMobility module=Sensors
time="2019-05-17T09:27:15+08:00" level=debug msg=prepare module=Positioning                                       
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoAddress module=Positioning        
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoAreaMonitorInfo module=Positioning  
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoAreaMonitorSource module=Positioning
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoCircle module=Positioning    
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoCoordinate module=Positioning
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoLocation module=Positioning
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoPath module=Positioning        
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoPositionInfo module=Positioning      
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoPositionInfoSource module=Positioning       
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoPositionInfoSourceFactory module=Positioning
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoRectangle module=Positioning    
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoSatelliteInfo module=Positioning      
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoSatelliteInfoSource module=Positioning
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QGeoShape module=Positioning              
time="2019-05-17T09:27:15+08:00" level=debug msg="failed to find header file" class=QNmeaPositionInfoSource module=Positioning
time="2019-05-17T09:27:15+08:00" level=debug msg=prepare module=Widgets
time="2019-05-17T09:27:16+08:00" level=debug msg=prepare module=Sql
time="2019-05-17T09:27:16+08:00" level=debug msg=prepare module=Qml                               
time="2019-05-17T09:27:16+08:00" level=debug msg="failed to find header file" class=QV4 module=Qml
```

**Comment by kuixiao** [comment] 2019-05-18 19:22
Have you solved this problem? I meet  with the same problem and don't know how to deal with it.

**Comment by kuixiao** [comment] 2019-05-18 19:23
Have you solved this problem? I meet with the same problem and don't know how to deal with it. Thanks

**Comment by therecipe** [comment] 2019-05-21 22:20
@idalin sorry for the delay, it could be that the issue was related to https://github.com/therecipe/qt/issues/814#issuecomment-492905248

But it should be fixed now with https://github.com/therecipe/qt/commit/8a927e9edb1f007b14c790445ec15a9c405bff83

I got it working as far as I could, but couldn't actually successful compile and link an application due the missing kindle libs.

Maybe test it again and check if the `qt/core/cgo_linux_*` file contains more than a few lines after running the setup (or qtdeploy).

@kuixiao Did you install Qt and then ran the setup?
If you just want to get it working real quick, then maybe use one of these instructions: https://github.com/therecipe/qt#installation

**Comment by idalin** [comment] 2019-05-22 08:07
> I got it working as far as I could, but couldn't actually successful compile and link an application due the missing kindle libs.
> 

kindle firmware: https://s3.amazonaws.com/firmwaredownloads/update_kindle_all_new_paperwhite_5.11.1.1.bin

can be extracted by https://github.com/NiLuJe/KindleTool

> Maybe test it again and check if the `qt/core/cgo_linux_*` file contains more than a few lines after running the setup (or qtdeploy).
> 
cat qt/core/cgo_linux_linux_arm.go
```go
// +build !minimal

package core

/*
#cgo CFLAGS: -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB 
#cgo CXXFLAGS: -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB 
#cgo CXXFLAGS: -I../../qt -I. -I/opt/kindle-qt5/target/include -I/opt/kindle-qt5/target/include/QtQuickWidgets -I/opt/kindle-qt5/target/include/QtWidgets -I/opt/kindle-qt5/target/include/QtQuick -I/opt/kindle-qt5/target/include/QtGui -I/opt/kindle-qt5/target/include/QtDBus -I/opt/kindle-qt5/target/include/QtQml -I/opt/kindle-qt5/target/include/QtNetwork -I/opt/kindle-qt5/target/include/QtTest -I/opt/kindle-qt5/target/include/QtCore -I. -I/opt/kindle-qt5/host/mkspecs/linux-g++
#cgo LDFLAGS: -O1 -Wl,-rpath,/mnt/us/qt/lib
#cgo LDFLAGS:  -L/opt/kindle-qt5/target/lib -lQt5QuickWidgets -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5DBus -lQt5Qml -lQt5Network -lQt5Test -lQt5Core -lGL -lpthread
#cgo CFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
#cgo CXXFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
*/
import "C"
```
--sysroot does not work. so it says `/home/dalin/opt/cross-gcc-linaro/lib/gcc/arm-linux-gnueabi/4.8.3/../../../../arm-linux-gnueabi/bin/ld: cannot find -lGL
`

**Comment by therecipe** [comment] 2019-05-22 22:42
Thanks, I will look into this tomorrow.
But the cgo file looks good so far.

About the sysroot, maybe try to comment out https://github.com/therecipe/qt/blob/master/internal/cmd/cmd.go#L735
and
https://github.com/therecipe/qt/blob/master/internal/cmd/setup/install.go#L119
and then try to run `qtsetup install` or `qtdeploy` again.

**Comment by idalin** [comment] 2019-05-24 07:31
Built successfully now.  but `qtdeploy build` failed for ldd can not recognize it as an executable file.

**Comment by therecipe** [comment] 2019-05-25 01:56
Ah, yeah it's probably using a wrong ldd version atm.
I will try to fix this tomorrow, but if you did copy the Qt libs onto you kindle (`/mnt/us/qt/lib`) then it probably should already work without this bundle/deployment step.

Maybe copy the binary onto your kindle and try to run it.

**Comment by idalin** [comment] 2019-05-25 07:14
> Ah, yeah it's probably using a wrong ldd version atm.
> I will try to fix this tomorrow, but if you did copy the Qt libs onto you kindle (`/mnt/us/qt/lib`) then it probably should already work without this bundle/deployment step.
> 
> Maybe copy the binary onto your kindle and try to run it.

sorry, i didn't tell.  and yes, it works! the problem is it runs very slow. Much slower than running with qmlscene(the gallery example).

**Closed** 2019-05-29 09:14 UTC

**Comment by therecipe** [comment] 2019-05-30 00:16
Hey

Sorry for the delay, it could be that the kindle is a bit underpowered for the go runtime or something.
But I also tested Go + Qt 5.6 on a raspberry pi 1 (256mb; 700MHz; armv6) and it seemed to work fine, so I'm not really sure. 

Maybe try to load the qml files from disk instead, and maybe also check if it runs faster on the second try. Because it could be that the qml engine tries to cache the qml files (create *.qmlc) at runtime, which might slow down the application in the first few seconds.
You can also disable the cache creation at runtime with `QML_DISABLE_DISK_CACHE=true`

**Comment by idalin** [comment] 2019-05-30 01:45
> edit: also I looked into the `ldd` issue and it seems like there is no proper `ldd` version shipped alongside the cross compiler, do you need to have the deployment/bundling of the libraries working as well?
> if not, then I will simply make it skip the bundling if it can't find a proper ldd version, so qtdeploy can exit without an issue
it would be better if the deployment/bundling of the libraries working as well.
ldd is just a shell script, maybe i can write one on my own

**Comment by therecipe** [comment] 2019-06-01 20:33
Okay, I will look into this.
I think I can probably make qtdeploy fallback to use objdump or something, to make it work as well.
