### ISSUE TITLE
qtsetup: QAbstractAnimation: No such file or directory

### ISSUE THREAD

**Issue by countstarlight** [therecipe/qt#814] opened 2019-03-29 03:44 UTC
I install `therecipe/qt` with package manager installed qt(Archlinux qt5.12.2) and test it's examples, works fine. But I want build static applicaion, So I built static qt with:
```bash
git clone https://code.qt.io/qt/qt5.git
cd qt5
git checkout 5.12
git submodule update --init --recursive
```
```bash
./configure -prefix /home/codist/data/qt5_static/5.12.0/gcc_64 \
            -sysconfdir /etc/xdg \
            -confirm-license \
            -opensource \
            -static \
            -dbus-linked \
            -openssl-linked \
            -system-harfbuzz \
            -system-sqlite \
            -qt-zlib \
            -qt-libpng \
            -qt-libjpeg \
            -opengl \
            -nomake examples \
            -nomake tests \
            -opengl && make -j8
```
And re run `qtsetup`:
```bash
qtsetup -qt_api 5.12.0 -qt_version 5.12.0 -qt_dir /home/codist/data/qt5_static
```
Ouput:
```
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/usr/local/go/bin/qtrcc); please use /home/countstarlight/data/work/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/usr/local/go/bin/qtmoc); please use /home/countstarlight/data/work/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/usr/local/go/bin/qtminimal); please use /home/countstarlight/data/work/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/usr/local/go/bin/qtdeploy); please use /home/countstarlight/data/work/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.11.4'      
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/codist/data/work' 
INFO[0000] GOBIN:                       '/home/codist/data/work/bin' 
INFO[0000] QT_HASH:                     '582f3233f09816df05444a042dd032151161772b' 
INFO[0000] QT_API:                   *  '5.12.0'        
INFO[0000] QT_VERSION:                  '5.12.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.12.0'        
INFO[0000] QT_DIR:                   *  '/home/codist/data/qt5_static' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'arch'          
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
INFO[0003] generating full qt/core                      
INFO[0020] generating full qt/androidextras             
INFO[0021] generating full qt/gui                       
INFO[0045] generating full qt/network                   
INFO[0052] generating full qt/xml                       
INFO[0054] generating full qt/dbus                      
INFO[0056] generating full qt/nfc                       
INFO[0057] generating full qt/script                    
INFO[0058] generating full qt/sensors                   
INFO[0065] generating full qt/positioning               
INFO[0066] generating full qt/widgets                   
INFO[0119] generating full qt/sql                       
INFO[0122] generating full qt/qml                       
INFO[0125] generating full qt/websockets                
INFO[0126] generating full qt/xmlpatterns               
INFO[0127] generating full qt/bluetooth                 
INFO[0130] generating full qt/webchannel                
INFO[0130] generating full qt/svg                       
INFO[0131] generating full qt/multimedia                
INFO[0146] generating full qt/quick                     
INFO[0151] generating full qt/help                      
INFO[0156] generating full qt/location                  
INFO[0158] generating full qt/scripttools               
INFO[0158] generating full qt/uitools                   
INFO[0158] generating full qt/webengine                 
INFO[0161] generating full qt/testlib                   
INFO[0161] generating full qt/serialport                
INFO[0162] generating full qt/serialbus                 
INFO[0164] generating full qt/printsupport              
INFO[0167] generating full qt/designer                  
INFO[0172] generating full qt/scxml                     
INFO[0174] generating full qt/gamepad                   
INFO[0175] generating full qt/purchasing                
INFO[0176] generating full qt/datavisualization    [GPLv3] 
INFO[0184] generating full qt/charts               [GPLv3] 
INFO[0195] generating full qt/speech                    
INFO[0196] generating full qt/quickcontrols2            
INFO[0196] generating full qt/sailfish                  
INFO[0196] generating full qt/webview                   
INFO[0196] generating full qt/remoteobjects             
INFO[0197] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0197] installing full qt/core                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

INFO[0346] installing full qt/androidextras
```
How to solve it?

**Comment by therecipe** [comment] 2019-03-29 22:26
Hey

Maybe try exporting
```
QT_QMAKE_DIR=/home/codist/data/qt5_static/5.12.0/gcc_64/bin
```
it's worth a try, but will probably not solve the issue.


Can you also show me the content of the cgo_linux* file inside the `therecipe/qt/core` folder?

And please post the output of
```
qtsetup -qt_api 5.12.0 -qt_version 5.12.0 -qt_dir /home/codist/data/qt5_static -debug generate
```
so I can look into the log

**Comment by countstarlight** [comment] 2019-03-30 01:52
I tried:
```bash
QT_QMAKE_DIR=/home/codist/data/qt5_static/5.12.0/gcc_64/bin qtsetup -qt_api 5.12.0 -qt_version 5.12.0 -qt_dir /home/codist/data/qt5_static
```
Output:
```
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/usr/local/go/bin/qtrcc); please use /home/codist/data/work/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/usr/local/go/bin/qtmoc); please use /home/codist/data/work/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/usr/local/go/bin/qtminimal); please use /home/codist/data/workbin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/usr/local/go/bin/qtdeploy); please use /home/codist/data/work/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.11.4'      
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/codist/data/work' 
INFO[0000] GOBIN:                       '/home/codist/data/work/bin' 
INFO[0000] QT_HASH:                     '582f3233f09816df05444a042dd032151161772b' 
INFO[0000] QT_API:                   *  '5.12.0'        
INFO[0000] QT_VERSION:                  '5.12.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.12.0'        
INFO[0000] QT_DIR:                   *  '/home/codist/data/qt5_static' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:             *  '/home/codist/data/qt5_static/5.12.0/gcc_64/bin' 
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'arch'          
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
INFO[0004] generating full qt/core                      
INFO[0019] generating full qt/androidextras             
INFO[0020] generating full qt/gui                       
INFO[0041] generating full qt/network                   
INFO[0048] generating full qt/xml                       
INFO[0050] generating full qt/dbus                      
INFO[0053] generating full qt/nfc                       
INFO[0055] generating full qt/script                    
INFO[0056] generating full qt/sensors                   
INFO[0062] generating full qt/positioning               
INFO[0064] generating full qt/widgets                   
INFO[0129] generating full qt/sql                       
INFO[0133] generating full qt/qml                       
INFO[0136] generating full qt/websockets                
INFO[0137] generating full qt/xmlpatterns               
INFO[0138] generating full qt/bluetooth                 
INFO[0142] generating full qt/webchannel                
INFO[0142] generating full qt/svg                       
INFO[0144] generating full qt/multimedia                
INFO[0161] generating full qt/quick                     
INFO[0166] generating full qt/help                      
INFO[0172] generating full qt/location                  
INFO[0174] generating full qt/scripttools               
INFO[0174] generating full qt/uitools                   
INFO[0174] generating full qt/webengine                 
INFO[0179] generating full qt/testlib                   
INFO[0180] generating full qt/serialport                
INFO[0180] generating full qt/serialbus                 
INFO[0182] generating full qt/printsupport              
INFO[0186] generating full qt/designer                  
INFO[0192] generating full qt/scxml                     
INFO[0194] generating full qt/gamepad                   
INFO[0195] generating full qt/purchasing                
INFO[0196] generating full qt/datavisualization    [GPLv3] 
INFO[0206] generating full qt/charts               [GPLv3] 
INFO[0218] generating full qt/speech                    
INFO[0218] generating full qt/quickcontrols2            
INFO[0218] generating full qt/sailfish                  
INFO[0218] generating full qt/webview                   
INFO[0218] generating full qt/remoteobjects             
INFO[0220] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0220] installing full qt/core                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

INFO[0365] installing full qt/androidextras
```

And in debug mode:
```bash
QT_QMAKE_DIR=/home/codist/data/qt5_static/5.12.0/gcc_64/bin qtsetup -qt_api 5.12.0 -qt_version 5.12.0 -qt_dir /home/codist/data/qt5_static -debug generate > qtsetup.log 2>&1
```
Output log file: [qtsetup.log](https://tooup.fun/file/get/373/qtsetup.log)(I can't access github-production-repository-file-5c1aeb.s3.amazonaws.com)

Only one cgo_linux* file inside the `therecipe/qt/core` folder,
`therecipe/qt/core/cgo_linux_linux_amd64.go`:
```golang
// +build !minimal

package core

/*
#cgo CFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
#cgo CXXFLAGS: -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
*/
import "C"

```

**Comment by therecipe** [comment] 2019-03-30 15:49
Thanks, yeah the cgo* file looks like I expected.

What's the output of the following?
```
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake -query QMAKE_SPEC
```

**Comment by countstarlight** [comment] 2019-03-31 05:35
> Thanks, yeah the cgo* file looks like I expected.
> 
> What's the output of the following?
> 
> ```
> /home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake -query QMAKE_SPEC
> ```

Output:
```
linux-g++
```

**Comment by therecipe** [comment] 2019-03-31 21:36
Thanks, this looks good so far.
Did you maybe move the Qt installation around after you build it?

Also could you post the output of the following?
```
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake -query
```
(and check if the paths are valid?)

And another thing, could you test this for me:

Create a `test.pro` file with the following content
```
QT=core
```

then run 

```
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake test.pro
```
and
```
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake test.pro -spec linux-g++
```

I expect that both of these commands will fail, however if the first one isn't could you post the created Makefile as well?

**Comment by countstarlight** [comment] 2019-04-02 04:54
Sorry for the late reply, I didn't move the Qt installation around after build it.

```bash
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake -query
```

Output:
```
QT_SYSROOT:
QT_INSTALL_PREFIX:/home/codist/data/qt5_static
QT_INSTALL_ARCHDATA:/home/codist/data/qt5_static
QT_INSTALL_DATA:/home/codist/data/qt5_static
QT_INSTALL_DOCS:/home/codist/data/qt5_static/doc
QT_INSTALL_HEADERS:/home/codist/data/qt5_static/include
QT_INSTALL_LIBS:/home/codist/data/qt5_static/lib
QT_INSTALL_LIBEXECS:/home/codist/data/qt5_static/libexec
QT_INSTALL_BINS:/home/codist/data/qt5_static/bin
QT_INSTALL_TESTS:/home/codist/data/qt5_static/tests
QT_INSTALL_PLUGINS:/home/codist/data/qt5_static/plugins
QT_INSTALL_IMPORTS:/home/codist/data/qt5_static/imports
QT_INSTALL_QML:/home/codist/data/qt5_static/qml
QT_INSTALL_TRANSLATIONS:/home/codist/data/qt5_static/translations
QT_INSTALL_CONFIGURATION:/etc/xdg
QT_INSTALL_EXAMPLES:/home/codist/data/qt5_static/examples
QT_INSTALL_DEMOS:/home/codist/data/qt5_static/examples
QT_HOST_PREFIX:/home/codist/data/qt5_static
QT_HOST_DATA:/home/codist/data/qt5_static
QT_HOST_BINS:/home/codist/data/qt5_static/bin
QT_HOST_LIBS:/home/codist/data/qt5_static/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:linux-g++
QMAKE_VERSION:3.1
QT_VERSION:5.12.3
```
As you expected, both of these commands was failed.
Create `test.pro` and run:

```bash
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake test.pro
```

Output:

```bash
Could not find qmake spec 'linux-g++'.
Error processing project file: test.pro
```

And

```bash
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake test.pro -spec linux-g++
```

Output:

```bash
Could not find qmake spec 'linux-g++'.
Error processing project file: test.pro
```

**Comment by therecipe** [comment] 2019-04-02 17:17
No problem, thanks yeah it seems like your installation is broken somehow.

Maybe try to create a file called `qt.conf` in `/home/codist/data/qt5_static/5.12.0/gcc_64/bin/`
with the following content:
```
[Paths]
Prefix=..
```

and then run `qmake -query` again

If you are lucky, then `QT_INSTALL_PREFIX` should point now to `/home/codist/data/qt5_static/5.12.0/gcc_64` and the other paths should be fixed as well.

Then try to run `qmake test.pro`, and if this also works then `qtsetup` should work as well.

**Comment by countstarlight** [comment] 2019-04-03 03:29
Thank you for your patience. Sorry, I forgot, I moved the Qt installation after build it. I used to build it with:
```bash
-prefix /home/codist/data/qt5_static
```
According `qtsetup` need, I moved `qt5_static` to `qt5_static/5.12.0/gcc_64`.
So I rebuild and reinstall it with:

```bash
-prefix /home/codist/data/qt5_static/5.12.0/gcc_64
```
and the

```bash
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake -query
```
Output:
```
QT_SYSROOT:
QT_INSTALL_PREFIX:/home/codist/data/qt5_static/5.12.0/gcc_64
QT_INSTALL_ARCHDATA:/home/codist/data/qt5_static/5.12.0/gcc_64
QT_INSTALL_DATA:/home/codist/data/qt5_static/5.12.0/gcc_64
QT_INSTALL_DOCS:/home/codist/data/qt5_static/5.12.0/gcc_64/doc
QT_INSTALL_HEADERS:/home/codist/data/qt5_static/5.12.0/gcc_64/include
QT_INSTALL_LIBS:/home/codist/data/qt5_static/5.12.0/gcc_64/lib
QT_INSTALL_LIBEXECS:/home/codist/data/qt5_static/5.12.0/gcc_64/libexec
QT_INSTALL_BINS:/home/codist/data/qt5_static/5.12.0/gcc_64/bin
QT_INSTALL_TESTS:/home/codist/data/qt5_static/5.12.0/gcc_64/tests
QT_INSTALL_PLUGINS:/home/codist/data/qt5_static/5.12.0/gcc_64/plugins
QT_INSTALL_IMPORTS:/home/codist/data/qt5_static/5.12.0/gcc_64/imports
QT_INSTALL_QML:/home/codist/data/qt5_static/5.12.0/gcc_64/qml
QT_INSTALL_TRANSLATIONS:/home/codist/data/qt5_static/5.12.0/gcc_64/translations
QT_INSTALL_CONFIGURATION:/etc/xdg
QT_INSTALL_EXAMPLES:/home/codist/data/qt5_static/5.12.0/gcc_64/examples
QT_INSTALL_DEMOS:/home/codist/data/qt5_static/5.12.0/gcc_64/examples
QT_HOST_PREFIX:/home/codist/data/qt5_static/5.12.0/gcc_64
QT_HOST_DATA:/home/codist/data/qt5_static/5.12.0/gcc_64
QT_HOST_BINS:/home/codist/data/qt5_static/5.12.0/gcc_64/bin
QT_HOST_LIBS:/home/codist/data/qt5_static/5.12.0/gcc_64/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:linux-g++
QMAKE_VERSION:3.1
QT_VERSION:5.12.3
```

Create `test.pro` and run:

```bash
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake test.pro 
```

Output:

```bash
Info: creating stash file /home/codist/.qmake.stash
```

And

```bash
/home/codist/data/qt5_static/5.12.0/gcc_64/bin/qmake test.pro -spec linux-g++
```

No output, remove `~/.qmake.stash` and re-run, the output same as above

Then

```bash
QT_QMAKE_DIR=/home/codist/data/qt5_static/5.12.0/gcc_64/bin qtsetup -qt_api 5.12.0 -qt_version 5.12.0 -qt_dir /home/codist/data/qt5_static
```

Output:

```
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/usr/local/go/bin/qtrcc); please use /home/codist/data/work/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/usr/local/go/bin/qtmoc); please use /home/codist/data/work/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/usr/local/go/bin/qtminimal); please use /home/codist/data/work/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/usr/local/go/bin/qtdeploy); please use /home/codist/data/work/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.11.4'      
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/codist/data/work' 
INFO[0000] GOBIN:                       '/home/codist/data/work/bin' 
INFO[0000] QT_HASH:                     '582f3233f09816df05444a042dd032151161772b' 
INFO[0000] QT_API:                   *  '5.12.0'        
INFO[0000] QT_VERSION:                  '5.12.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.12.0'        
INFO[0000] QT_DIR:                   *  '/home/codist/data/qt5_static' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:             *  '/home/codist/data/qt5_static/5.12.0/gcc_64/bin' 
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'arch'          
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
INFO[0004] generating full qt/core                      
INFO[0025] generating full qt/androidextras             
INFO[0026] generating full qt/gui                       
INFO[0054] generating full qt/network                   
INFO[0066] generating full qt/xml                       
INFO[0068] generating full qt/dbus                      
INFO[0075] generating full qt/nfc                       
INFO[0076] generating full qt/script                    
INFO[0081] generating full qt/sensors                   
INFO[0091] generating full qt/positioning               
INFO[0097] generating full qt/widgets                   
INFO[0160] generating full qt/sql                       
INFO[0168] generating full qt/qml                       
INFO[0174] generating full qt/websockets                
INFO[0179] generating full qt/xmlpatterns               
INFO[0183] generating full qt/bluetooth                 
INFO[0187] generating full qt/webchannel                
INFO[0191] generating full qt/svg                       
INFO[0196] generating full qt/multimedia                
INFO[0215] generating full qt/quick                     
INFO[0225] generating full qt/help                      
INFO[0233] generating full qt/location                  
INFO[0239] generating full qt/scripttools               
INFO[0242] generating full qt/uitools                   
INFO[0246] generating full qt/webengine                 
INFO[0249] generating full qt/testlib                   
INFO[0253] generating full qt/serialport                
INFO[0257] generating full qt/serialbus                 
INFO[0262] generating full qt/printsupport              
INFO[0265] generating full qt/designer                  
INFO[0275] generating full qt/scxml                     
INFO[0280] generating full qt/gamepad                   
INFO[0285] generating full qt/purchasing                
INFO[0289] generating full qt/datavisualization    [GPLv3] 
INFO[0299] generating full qt/charts               [GPLv3] 
INFO[0310] generating full qt/speech                    
INFO[0314] generating full qt/quickcontrols2            
INFO[0317] generating full qt/sailfish                  
INFO[0317] generating full qt/webview                   
INFO[0321] generating full qt/remoteobjects             
INFO[0326] running: 'qtsetup install linux' [docker=false] [vagrant=false] 
INFO[0326] installing full qt/core                      
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:10: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

INFO[0474] installing full qt/androidextras
```

**Comment by therecipe** [comment] 2019-04-04 20:19
Okay, this looks good so far.
Could you please upload the new log of `qtsetup -debug generate`?

I'm currently trying to get a static linux docker image working, and figured that you will probably need to re-compile Qt with `-skip qtfeedback` again to get it working.

**Comment by therecipe** [comment] 2019-04-09 20:46
Hey, I got a static linux docker image working (`linux_static`)

To get it working yourself, you will need to compile Qt with `-skip qtfeedback` like it's shown [here](https://github.com/therecipe/qt/blob/master/internal/docker/linux/Dockerfile.static_base#L13)
and also export `QT_STATIC=true`, like it's shown [here](https://github.com/therecipe/qt/blob/master/internal/docker/linux/Dockerfile.static#L21)

**Comment by fdgonthier** [comment] 2019-05-16 03:44
I'm having the same problem has the gentleman here but I'm using distribution Qt5 packages in Debian Sid. Here is my qtsetup.log.

[qtsetup.log](https://github.com/therecipe/qt/files/3185307/qtsetup.log)

**Comment by therecipe** [comment] 2019-05-16 04:02
@fdgonthier
Hey, it seems like you are missing the Qt "svg" module. (It's currently mandatory to have it installed)
Maybe try to install `libqt5svg5-dev` and run the setup again.

Alternativly, run  `sudo apt-get --no-install-recommends install libqt*5-dev qt*5-dev qml-module-qtquick-* qt*5-doc-html`.

It might be that the setup throws some warnings/errors at you, because of the other missing modules (xmlpatterns, sensors, websockets, ...), but if you don't plan to use them than you can just ignore these warnings.

If everything works as espected, than the setup should build and start some examples during the end of the setup.

**Comment by therecipe** [comment] 2019-05-21 22:10
The svg module is now optional with https://github.com/therecipe/qt/commit/8a927e9edb1f007b14c790445ec15a9c405bff83

I will close this now, but for the reference the static linux docker image is called `linux_static` and can be used like this `qtdeploy -docker build linux_static` now

**Closed by therecipe** 2019-05-21 22:10 UTC

**Comment by AhmedMKamal** [comment] 2019-12-26 09:55
@therecipe I'm having the same issue on Windows 10 machine, I've followed the installation tut [here](https://github.com/therecipe/qt/wiki/Installation-on-Windows#official-version-with-android-support) but the only difference was that I've installed version `5.14.0` of Qt, the issue is that when I'm running `%GOPATH%\bin\qtsetup.exe` it fails with the following log

```
λ qtsetup.exe
time="2019-12-26T06:16:57+02:00" level=info msg="successfully created qtenv.bat symlink in your PATH (c:\\go\\bin\\qtenv.bat)"
time="2019-12-26T06:16:57+02:00" level=info msg="running: 'qtsetup prep'"
time="2019-12-26T06:16:57+02:00" level=warning msg="failed to create qtrcc symlink in your PATH (c:\\go\\bin\\qtrcc.exe); please use E:\\WorkSpace\\Golang\\bin\\qtrcc.exe instead"
time="2019-12-26T06:16:57+02:00" level=warning msg="failed to create qtmoc symlink in your PATH (c:\\go\\bin\\qtmoc.exe); please use E:\\WorkSpace\\Golang\\bin\\qtmoc.exe instead"
time="2019-12-26T06:16:57+02:00" level=warning msg="failed to create qtminimal symlink in your PATH (c:\\go\\bin\\qtminimal.exe); please use E:\\WorkSpace\\Golang\\bin\\qtminimal.exe instead"
time="2019-12-26T06:16:57+02:00" level=warning msg="failed to create qtdeploy symlink in your PATH (c:\\go\\bin\\qtdeploy.exe); please use E:\\WorkSpace\\Golang\\bin\\qtdeploy.exe instead"
time="2019-12-26T06:16:58+02:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2019-12-26T06:16:58+02:00" level=info msg="GOOS:                        'windows'"
time="2019-12-26T06:16:58+02:00" level=info msg="GOARCH:                      'amd64'"
time="2019-12-26T06:16:58+02:00" level=info msg="GOVERSION:                   'go1.13.5'"
time="2019-12-26T06:16:58+02:00" level=info msg="GOROOT:                      'c:\\go'"
time="2019-12-26T06:16:58+02:00" level=info msg="GOPATH:                   *  'E:\\WorkSpace\\Golang'"
time="2019-12-26T06:16:58+02:00" level=info msg="GOBIN:                       'E:\\WorkSpace\\Golang\\bin'"
time="2019-12-26T06:16:58+02:00" level=info msg="GOMOD:                       ''"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_HASH:                     '4ee12d6ea9262c808871052f0f23c409c930d5ae'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_API:                      ''"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_VERSION:               *  '5.14.0'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_DIR:                   *  'C:\\Qt\\Qt5.14.0'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_STUB:                     'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_DEBUG:                    'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_WEBKIT:                   'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_STATIC:                   'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_GEN_TSD:                  'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_GEN_OPENGL:               'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_GEN_QUICK_EXTRAS:         'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_RESOURCES_BIG:            'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_NOT_CACHED:               'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_DEBUG_CONSOLE:            'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="QT_MSYS2:                    'false'"
time="2019-12-26T06:16:58+02:00" level=info msg="running: 'qtsetup generate windows' [docker=false] [vagrant=false]"
time="2019-12-26T06:17:10+02:00" level=info msg="generating full qt/core"
time="2019-12-26T06:17:35+02:00" level=info msg="generating full qt/androidextras"
time="2019-12-26T06:17:38+02:00" level=info msg="generating full qt/gui"
time="2019-12-26T06:18:12+02:00" level=info msg="generating full qt/network"
time="2019-12-26T06:18:21+02:00" level=info msg="generating full qt/xml"
time="2019-12-26T06:18:24+02:00" level=info msg="generating full qt/dbus"
time="2019-12-26T06:18:28+02:00" level=info msg="generating full qt/nfc"
time="2019-12-26T06:18:31+02:00" level=info msg="generating full qt/script"
time="2019-12-26T06:18:34+02:00" level=info msg="generating full qt/sensors"
time="2019-12-26T06:18:42+02:00" level=info msg="generating full qt/positioning"
time="2019-12-26T06:18:45+02:00" level=info msg="generating full qt/widgets"
time="2019-12-26T06:19:57+02:00" level=info msg="generating full qt/sql"
time="2019-12-26T06:20:03+02:00" level=info msg="generating full qt/qml"
time="2019-12-26T06:20:07+02:00" level=info msg="generating full qt/websockets"
time="2019-12-26T06:20:09+02:00" level=info msg="generating full qt/xmlpatterns"
time="2019-12-26T06:20:11+02:00" level=info msg="generating full qt/bluetooth"
time="2019-12-26T06:20:16+02:00" level=info msg="generating full qt/webchannel"
time="2019-12-26T06:20:17+02:00" level=info msg="generating full qt/svg"
time="2019-12-26T06:20:19+02:00" level=info msg="generating full qt/multimedia"
time="2019-12-26T06:20:38+02:00" level=info msg="generating full qt/quick"
time="2019-12-26T06:20:45+02:00" level=info msg="generating full qt/help"
time="2019-12-26T06:20:52+02:00" level=info msg="generating full qt/location"
time="2019-12-26T06:20:55+02:00" level=info msg="generating full qt/scripttools"
time="2019-12-26T06:20:56+02:00" level=info msg="generating full qt/uitools"
time="2019-12-26T06:20:57+02:00" level=info msg="generating full qt/winextras"
time="2019-12-26T06:20:59+02:00" level=info msg="generating full qt/testlib"
time="2019-12-26T06:21:00+02:00" level=info msg="generating full qt/serialport"
time="2019-12-26T06:21:02+02:00" level=info msg="generating full qt/serialbus"
time="2019-12-26T06:21:05+02:00" level=info msg="generating full qt/printsupport"
time="2019-12-26T06:21:09+02:00" level=info msg="generating full qt/designer"
time="2019-12-26T06:21:16+02:00" level=info msg="generating full qt/scxml"
time="2019-12-26T06:21:18+02:00" level=info msg="generating full qt/gamepad"
time="2019-12-26T06:21:20+02:00" level=info msg="generating full qt/purchasing"
time="2019-12-26T06:21:21+02:00" level=info msg="generating full qt/datavisualization    [GPLv3]"
time="2019-12-26T06:21:28+02:00" level=info msg="generating full qt/charts               [GPLv3]"
time="2019-12-26T06:21:42+02:00" level=info msg="generating full qt/virtualkeyboard      [GPLv3]"
time="2019-12-26T06:21:45+02:00" level=info msg="generating full qt/speech"
time="2019-12-26T06:21:47+02:00" level=info msg="generating full qt/quickcontrols2"
time="2019-12-26T06:21:48+02:00" level=info msg="generating full qt/sailfish"
time="2019-12-26T06:21:48+02:00" level=info msg="generating full qt/remoteobjects"
time="2019-12-26T06:22:00+02:00" level=info msg="running: 'qtsetup install windows' [docker=false] [vagrant=false]"
time="2019-12-26T06:22:00+02:00" level=info msg="installing full qt/core"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:10:3: error: #error ------------------------------------------------------------------
  #error ------------------------------------------------------------------
   ^~~~~
core.cpp:11:3: error: #error please run: '$(go env GOPATH)/bin/qtsetup'
  #error please run: '$(go env GOPATH)/bin/qtsetup'
   ^~~~~
core.cpp:12:3: error: #error more info here: https:
  #error more info here: https://github.com/therecipe/qt/wiki/Installation
   ^~~~~
core.cpp:13:3: error: #error ------------------------------------------------------------------
  #error ------------------------------------------------------------------
   ^~~~~
core.cpp:15:10: fatal error: QAbstractAnimation: No such file or directory
 #include <QAbstractAnimation>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

time="2019-12-26T06:26:11+02:00" level=error msg="failed to install 'core'; aborting setup"
```

any ideas?

**Comment by rhardock** [comment] 2020-03-07 10:07
I'm also having the same issue on Windows 10 as AhmedMKamal.  Any solution?

**Comment by ergoz** [comment] 2020-03-20 23:53
same problem.... i tried a lot of variants with no luck

**Comment by trueafrit** [comment] 2022-01-11 13:19
same trouble with windows 10
