### ISSUE TITLE
Can't turn on hDPI with qtdeploy

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#76] opened 2016-10-21 07:08 UTC
As `qtdeploy` don't log anything, I can't troubleshoot this issue myself (see issue #72).

On OSX with Retina display all applications built do not look good, as they use lower DPI rendering:

<img width="475" alt="image-1" src="https://cloud.githubusercontent.com/assets/474302/19589430/c2c178e4-979e-11e6-9a00-478a234c6ad4.png">

I could fixed this by using this change:

```
diff --git a/internal/examples/qml/application/application.go b/internal/examples/qml/application/application.go
index 152ac48..456a5f0 100755
--- a/internal/examples/qml/application/application.go
+++ b/internal/examples/qml/application/application.go
@@ -10,7 +10,9 @@ import (

 func main() {

-       gui.NewQGuiApplication(len(os.Args), os.Args)
+       a := gui.NewQGuiApplication(len(os.Args), os.Args)
+       a.SetAttribute(core.Qt__AA_UseHighDpiPixmaps, true)
+       a.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

        var app = qml.NewQQmlApplicationEngine(nil)
        app.Load(core.NewQUrl3("qrc:///qml/application.qml", 0))
```

and then rebuild the and run:

```
src/github.com/therecipe/qt/internal/examples/qml/application go build -v
github.com/therecipe/qt/internal/examples/qml/application
./application
```

and then it look correctly:

<img width="480" alt="image-2" src="https://cloud.githubusercontent.com/assets/474302/19589481/f405ea52-979e-11e6-9208-2aca68870b8e.png">

I even tried to run with `go build -v -a` (force rebuild of all .go source) and it successfully build & run.

but if I build that with `qtdeploy` I get the following error:

```
# github.com/therecipe/qt/internal/examples/qml/application
./application.go:14: a.SetAttribute undefined (type *gui.QGuiApplication has no field or method SetAttribute)
./application.go:15: a.SetAttribute undefined (type *gui.QGuiApplication has no field or method SetAttribute)

error:exit status 2
```

**Comment by therecipe** [comment] 2016-10-21 19:26
There seems to be a problem with the minimal build, which is generated on the fly by analyzing the code.

I will look into this.

**Comment by therecipe** [comment] 2016-10-21 22:25
Should be fixed with https://github.com/therecipe/qt/commit/82145c26be44d89d6e07f4d316fae0812271bc65

The `SetAttribute` function is a static Qt function and wasn't recognized by 
qtdeploy.

**Comment by bclermont** [comment] 2016-10-24 09:34
I can confirm the build error is gone, but the display stays the same (ugly fonts), even if I call `SetAttribute`.
Like if the the call actually do nothing.

Any idea?

**Comment by therecipe** [comment] 2016-10-24 15:45
I'm sorry, my mac has no retina display and therefore I can't reproduce it. 
But could you check if the attributes are really set with `a.TestAttribute(...)`?

**Comment by bclermont** [comment] 2016-10-25 08:25
```
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
	"fmt"
	"time"
)

func main() {

	a := gui.NewQGuiApplication(len(os.Args), os.Args)
	fmt.Println("BEFORE SET ATTRIBUTE")
	fmt.Printf("Before AA_UseHighDpiPixmaps: %t\n", a.TestAttribute(core.Qt__AA_UseHighDpiPixmaps))
	fmt.Printf("Before: AA_EnableHighDpiScaling: %t\n", a.TestAttribute(core.Qt__AA_EnableHighDpiScaling))

	a.SetAttribute(core.Qt__AA_UseHighDpiPixmaps, true)
	a.SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	fmt.Println("AFTER SET ATTRIBUTE")

	fmt.Printf("After AA_UseHighDpiPixmaps: %t\n", a.TestAttribute(core.Qt__AA_UseHighDpiPixmaps))
	fmt.Printf("After: AA_EnableHighDpiScaling: %t\n", a.TestAttribute(core.Qt__AA_EnableHighDpiScaling))

	var app = qml.NewQQmlApplicationEngine(nil)
	app.Load(core.NewQUrl3("file:////Users/ben/sandbox/wl/godeps/src/github.com/therecipe/qt/internal/examples/qml/application/qml/application.qml", 0))

	go func() {
		time.Sleep(5 * time.Second)

		fmt.Printf("Post exec: AA_UseHighDpiPixmaps: %t\n", a.TestAttribute(core.Qt__AA_UseHighDpiPixmaps))
		fmt.Printf("Post exec: AA_EnableHighDpiScaling: %t\n", a.TestAttribute(core.Qt__AA_EnableHighDpiScaling))
	}()

	fmt.Println("Exec application")
	gui.QGuiApplication_Exec()
}
```

output is :

```
deploy/darwin_minimal/application.app/Contents/MacOS/application_app
BEFORE SET ATTRIBUTE
Before AA_UseHighDpiPixmaps: false
Before: AA_EnableHighDpiScaling: false
AFTER SET ATTRIBUTE
After AA_UseHighDpiPixmaps: true
After: AA_EnableHighDpiScaling: true
Exec application
Post exec: AA_UseHighDpiPixmaps: true
Post exec: AA_EnableHighDpiScaling: true
```

so... `SetAttribute` really worked

but the resolution is bad.

but If I do:

```
$ cp deploy/darwin_minimal/application.app/Contents/MacOS/application_app /tmp/zzz
$ /tmp/zzz
```

it look good! something is wrong in `Contents/MacOS` and I can't figure what

**Comment by therecipe** [comment] 2016-10-25 14:00
Could you replace
```
<key>NSHighResolutionCapable</key>
<string>True</string>
```
with 
```
<key>NSHighResolutionCapable</key>
<true/>
```

in the MacOS/Info.plist and try again?

That should work according to the [Apple Docs](https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html#//apple_ref/doc/uid/TP40012302-CH4-SW3).

**Comment by bclermont** [comment] 2016-10-25 14:46
> in the MacOS/Info.plist and try again?

No :|

I looked around to compare with other real examples in `/Applications` such as `VLC.app` and there is not even `Info.plist` in `MacOS/` :)

https://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

```
<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<string>True</string>
```

tried. what is very weird is that, outside the `Contents/MacOS` directory, resolution is just right.

**Comment by therecipe** [comment] 2016-10-25 14:49
Could you move the Info.plist one up into the Contents folder?
I checked my Applications as well and all got them in the Contents folder.

**Comment by bclermont** [comment] 2016-10-25 15:04
> Could you move the Info.plist one up into the Contents folder?

you nailed it!

`qtdeploy` must create `Info.plist` into `Contents` and not `Contents/MacOS`

**Closed** 2016-10-25 15:11 UTC

**Comment by therecipe** [comment] 2016-10-25 15:13
Thanks, it's merged :)
