### ISSUE TITLE
qtdeplay fails to compile

### ISSUE THREAD

**Issue by Aquarian-Age** [therecipe/qt#1051] opened 2020-01-23 00:49 UTC
I use openSUSE 15.1

~/nfs_share/golang/qt-go/examples
liangzi@xuan 19 08:46 >qtsetup check
```
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.13.6'      
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/xuan/go_work' 
INFO[0000] GOBIN:                       '/home/xuan/go_work/bin' 
INFO[0000] GOMOD:                       '/home/xuan/nfs_share/golang/qt-go/examples/go.mod' 
INFO[0000] QT_HASH:                     'v0.0.0-20200103041036-2b818d970888' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:               *  '5.13.2'        
INFO[0000] QT_DIR:                   *  '/home/xuan/Qt' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_STATIC:                   'false'         
INFO[0000] QT_GEN_TSD:                  'false'         
INFO[0000] QT_GEN_OPENGL:               'false'         
INFO[0000] QT_GEN_QUICK_EXTRAS:         'false'         
INFO[0000] QT_RESOURCES_BIG:            'false'         
INFO[0000] QT_NOT_CACHED:               'false'         
INFO[0000] QT_DISTRO:                   'fedora'        
INFO[0000] QT_PKG_CONFIG:               'false'
```

~/nfs_share/golang/qt-go/examples
liangzi@xuan 20 08:47 >qtdeploy -fast test desktop github.com/therecipe/examples/advanced/widgets/tableview

ERRO[0000] failed to run command                         _func=RunCmd cmd="bash -c /usr/local/go/bin/go build -p 4 -v -trimpath -o /home/xuan/nfs_share/golang/qt-go/examples/advanced/widgets/tableview/deploy/linux/tableview -tags= -ldflags=all=\"-s\" \"-w\"" dir=/home/xuan/nfs_share/golang/qt-go/examples/advanced/widgets/tableview env="HOST=liangzi.local XNLSPATH=/usr/share/X11/nls XDG_SESSION_CLASS=user XCURSOR_THEME=KDE_Classic ANDROID_HOME=/home/xuan/Android/Sdk HOSTNAME=liangzi.local KONSOLE_DBUS_SERVICE=:1.278 LOGNAME=xuan QT_IM_SWITCHER=imsw-multi GOPATH=/home/xuan/go_work COLORTERM=truecolor LC_CTYPE=zh_CN.UTF-8 SSH_AGENT_PID=7205 SDK_HOME=/usr/lib64/jvm/java _ModuleTable_Sz_=1 MODULEPATH=/usr/share/lmod/modulefiles CONFIG_SITE=/usr/share/site/x86_64-unknown-linux-gnu QT_SYSTEM_DIR=/usr/share/desktop-data MAN_POSIXLY_CORRECT=1 MORE=-sl NNTPSERVER=news KONSOLE_DBUS_SESSION=/Sessions/1 QT_AUTO_SCREEN_SCALE_FACTOR=0 ALSA_CONFIG_PATH=/etc/alsa-pulse.conf SHELL=/bin/bash XDG_CURRENT_DESKTOP=KDE XAUTHORITY=/home/xuan/.Xauthority XDG_CONFIG_DIRS=/etc/xdg CVS_RSH=ssh CGO_LDFLAGS= LS_COLORS=no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.xz=00;31:*.avi=01;35:*.bmp=01;35:*.dl=01;35:*.fli=01;35:*.gif=01;35:*.gl=01;35:*.jpg=01;35:*.jpeg=01;35:*.mkv=01;35:*.mng=01;35:*.mov=01;35:*.mp4=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.svg=01;35:*.tga=01;35:*.tif=01;35:*.webm=01;35:*.webp=01;35:*.wmv=01;35:*.xbm=01;35:*.xcf=01;35:*.xpm=01;35:*.aiff=00;32:*.ape=00;32:*.au=00;32:*.flac=00;32:*.m4a=00;32:*.mid=00;32:*.mp3=00;32:*.mpc=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:*.wma=00;32:*.wv=00;32: QT_DIR=/home/xuan/Qt QT_IM_MODULE=fcitx MANPATH=/usr/local/man:/usr/local/share/man:/usr/share/man:/opt/kde3/share/man:/usr/man:/usr/brlcad/rel-7.26.0/share/man KDE_SESSION_UID=1005 PATH=/home/xuan/.local/bin:/opt/android-studio/bin:/usr/local/GoLand/bin:/home/xuan/go_work/bin:/usr/local/go/bin:/home/xuan/.cargo/bin:/home/xuan/.local/bin:/opt/android-studio/bin:/usr/local/GoLand/bin:/home/xuan/go_work/bin:/usr/local/go/bin:/home/xuan/bin:/usr/local/bin:/usr/bin:/bin:/opt/kde3/bin:/home/xuan/.dotnet/tools:/usr/lib/mit/bin:/usr/lib/mit/sbin:/snap/bin:/home/xuan/Android/Sdk/tools:/home/xuan/Android/Sdk/platform-tools:/home/xuan/dotnet:/home/xuan/.dotnet/tools:/home/xuan/Android/Sdk/tools:/home/xuan/Android/Sdk/platform-tools:/home/xuan/dotnet:/home/xuan/.dotnet/tools XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB QT_VERSION=5.13.2 XDG_SESSION_ID=7 PYTHONSTARTUP=/etc/pythonstart LMOD_PREPEND_BLOCK=normal LESSOPEN=lessopen.sh %s OLDPWD=/home/xuan/nfs_share/golang/qt-go/examples/test XDG_RUNTIME_DIR=/run/user/1005 JAVA_BINDIR=/usr/lib64/jvm/java/bin SESSION_MANAGER=local/liangzi.local:@/tmp/.ICE-unix/7314,unix/liangzi.local:/tmp/.ICE-unix/7314 BASH_FUNC_module%%=() {  eval $($LMOD_CMD bash \"$@\") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)\n} _=/home/xuan/go_work/bin/qtdeploy MAN_KEEP_FORMATTING=yes JAVA_HOME=/usr/lib64/jvm/java XDG_VTNR=7 G_BROKEN_FILENAMES=1 GOFLAGS=-mod=vendor LESS=-M -I -R USER=xuan KONSOLE_DBUS_WINDOW=/Windows/1 GOARCH=amd64 CSHEDIT=emacs DOTNET_ROOT=/home/xuan/dotnet XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session6 GS_LIB=/home/xuan/.fonts SHELL_SESSION_ID=3fbab8b660c7424f91183a28830b3c8f QEMU_AUDIO_DRV=pa HOME=/home/xuan FROM_HEADER= AUDIODRIVER=pulseaudio MACHTYPE=x86_64-suse-linux LANG=zh_CN.UTF-8 HISTFILESIZE=90000 PWD=/home/xuan/nfs_share/golang/qt-go/examples XDG_DATA_DIRS=/home/xuan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/etc/opt/kde3/share:/opt/kde3/share SHLVL=2 WINDOWID=6291462 MINICOM=-c on PAGER=less XDG_SESSION_DESKTOP=KDE INPUT_METHOD=fcitx BASH_FUNC_mc%%=() {  . /usr/share/mc/mc-wrapper.sh\n} DESKTOP_SESSION=/usr/share/xsessions/plasma5 LMOD_SETTARG_CMD=: BASH_ENV=/usr/share/lmod/7.6.1/init/bash XSESSION_IS_UP=yes PS1=\\w\\n\\h@\\u \\# \\A > HISTSIZE=90000 KDE_FULL_SESSION=true KONSOLE_VERSION=181203 RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static KDED_STARTED_BY_KDEINIT=1 MODULESHOME=/usr/share/lmod/lmod PILOTPORT=usb: PROFILEHOME= XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0 LS_OPTIONS=-N --color=tty -T 0 LMOD_DIR=/usr/share/lmod/lmod/libexec GOOS=linux DISPLAY=:0 _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii91c3Ivc2hhcmUvbG1vZC9tb2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL2xtb2QvbW9kdWxlZmlsZXMiLH0= GTK_MODULES=canberra-gtk-module DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1005/bus XMODIFIERS=@im=fcitx RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup KONSOLE_PROFILE_NAME=配置方案 1 KDE_SESSION_VERSION=5 HOSTTYPE=x86_64 LESS_ADVANCED_PREPROCESSOR=no SSH_AUTH_SOCK=/tmp/ssh-OFkDiCOcAcl7/agent.7094 XCURSOR_SIZE=0 XDG_SESSION_TYPE=x11 BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd \"$@\")\n} GPG_TTY=/dev/pts/0 OSTYPE=linux LMOD_COLORIZE=no SDL_AUDIODRIVER=pulse CPU=x86_64 GOROOT=/usr/local/go LC_ALL=zh_CN.UTF-8 LANGUAGE=zh_CN:zh_TW LMOD_FULL_SETTARG_SUPPORT=no GTK_IM_MODULE=fcitx LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod LESSCLOSE=lessclose.sh %s %s HISTTIMEFORMAT=%Y.%m.%d-%T ::  MAIL=/var/spool/mail/xuan LESSKEY=/etc/lesskey.bin G_FILENAME_ENCODING=@locale,UTF-8,GB2312,GB18030,GBK,ISO-8859-1 WINDOWMANAGER=/usr/bin/startkde VDPAU_DRIVER=va_gl JDK_HOME=/usr/lib64/jvm/java PROFILEREAD=true CGO_ENABLED=1 XAUTHLOCALHOSTNAME=liangzi.local LMOD_VERSION=7.6.1 COLORFGBG=15;0 JRE_HOME=/usr/lib64/jvm/java/jre JAVA_ROOT=/usr/lib64/jvm/java SSH_ASKPASS=/usr/lib/ssh/ssh-askpass TERM=xterm-256color XDG_SEAT=seat0 LMOD_PKG=/usr/share/lmod/lmod" error="exit status 2" name="build for linux on linux"
flag provided but not defined: -w
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.

**Comment by therecipe** [comment] 2020-01-25 19:16
Hey

This seems to be a duplicate of https://github.com/therecipe/qt/issues/1045, I will look into this.

**Closed** 2022-03-21 19:51 UTC
