### ISSUE TITLE
Error to paint on QWidget 

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#250] opened 2017-03-18 00:58 UTC
Hi, ConnectPaintEvent on a QWdiget, and in the event calling gui.NewQPainter2(widget); I get this error: QPainter::begin: A paint device can only be painted by one painter at a time.

**Comment by therecipe** [comment] 2017-03-18 18:18
Hey

I had similar problems myself when I ported the [rasterwindow](https://github.com/therecipe/qt/blob/master/internal/examples/gui/analogclock/rasterwindow.go) example.

IIRC the solution was to destroy the painter, after each update:
https://github.com/therecipe/qt/blob/master/internal/examples/gui/analogclock/rasterwindow.go#L72

I guess you could instead cache the painter as well, but I never tested that.

**Comment by dzhou121** [comment] 2017-03-18 18:56
Thanks for your reply. I've tried it but it doesn't work QWidget somehow. It just throws this error the first time I call gui.NewQPainter2(widget); even call this straight after NewQWidget, which would definitely only call NewQPainter2 once.

**Comment by therecipe** [comment] 2017-03-18 19:17
Could you post a small snipped, so I can reproduce it?

**Comment by dzhou121** [comment] 2017-03-18 19:19
Sure

```
package main

import (
	"os"

	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	//create a window
	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowTitle("Hello World Example")
	window.SetMinimumSize2(200, 200)

	centralWidget := widgets.NewQWidget(window, 0)

	canvas := widgets.NewQWidget(centralWidget, 0)
	canvas.Resize2(100, 100)
	canvas.SetStyleSheet("background-color: rgba(0, 0, 0, 1);")
	canvas.ConnectPaintEvent(func(vqp *gui.QPaintEvent) {
		p := gui.NewQPainter2(canvas)
		color := gui.NewQColor()
		color.SetRgb(255, 255, 255, 1)
		p.SetPen2(color)
		p.DrawText3(10, 10, "test test")
		p.DestroyQPainter()
	})
	window.SetCentralWidget(centralWidget)
	window.Show()

	widgets.QApplication_Exec()
}

```

**Comment by dzhou121** [comment] 2017-03-18 20:27
I know little about C++, but do you think it to do with

```
return new QPainter(device);
```

I see in the documentation, you just

```
QPainter p(device);
```

Does the ```new``` makes any difference here?

**Comment by therecipe** [comment] 2017-03-18 20:33
I could reproduce it, but I'm not yet sure what's causing it.

>Does the new makes any difference here?

I honestly don't know, but it could be. (I will test it)

What I figured was, that `canvas.PaintingActive()` if called from within the PaintEvent function,
always returns true. And it should return false afaik, so that you can take over with your own painter.

**Comment by dzhou121** [comment] 2017-03-18 20:35
It sounds like when a QWidget is created, a QPainter is also created on the device somewhere.

**Comment by dzhou121** [comment] 2017-03-18 20:44
canvas.PaintingActive() is true straight after widgets.NewQWidget, event if not to ConnectPaintEvent

**Comment by therecipe** [comment] 2017-03-18 21:36
I just tested it in C++, there you can use `new QPainter(device)` if you destroy the painter afterwards.
And `paintingActive()` always returns false, when called from within the `paintEvent` function.

**Comment by therecipe** [comment] 2017-03-18 21:58
I think I got it.
The problem is that the `NewQPainter` functions, can't handle polymorphic inputs.
There were a few similar issues like this already. One of them is: https://github.com/therecipe/qt/issues/156

I will fix it.

**Comment by dzhou121** [comment] 2017-03-19 15:38
Thank you for the help. Look forward to the fix.

**Comment by therecipe** [comment] 2017-03-20 17:40
Should be fixed now with: https://github.com/therecipe/qt/commit/b2418c2c226649350c037078f287e500e306f545

Maybe try to use `qtsetup upgrade && qtsetup`

**Comment by dzhou121** [comment] 2017-03-20 18:38
Thanks @therecipe 

I've just tried it and the error is gone; but the draw seems not to do anything

```
package main

import (
	"os"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	//create a window
	window := widgets.NewQMainWindow(nil, 0)
	window.SetWindowTitle("Hello World Example")
	window.SetMinimumSize2(200, 200)

	centralWidget := widgets.NewQWidget(window, 0)

	widget := widgets.NewQWidget(centralWidget, 0)
	widget.SetStyleSheet("background-color: rgba(0, 0, 0, 0.5)")
	widget.Resize2(100, 100)
	widget.Move2(10, 10)

	widget.ConnectPaintEvent(func(paint *gui.QPaintEvent) {
		p := gui.NewQPainter2(widget)
		f := gui.NewQFont2("", 14, 1, false)
		color := gui.NewQColor3(255, 255, 255, 1)
		p.FillRect5(0, 0, 30, 30, color)
		p.SetPen2(color)
		p.SetFont(f)
		p.DrawText2(core.NewQPoint2(20, 20), "test test")
		p.DestroyQPainter()
	})

	window.SetCentralWidget(centralWidget)
	window.Show()

	widgets.QApplication_Exec()
}

```

**Comment by therecipe** [comment] 2017-03-20 19:18
You just need to use a greater value for "a" when you create your rgba based color.

Like this:
`color := gui.NewQColor3(255, 255, 255, 255)`
http://doc.qt.io/qt-5/qcolor.html#QColor-2 (255 is the default for "a")

It's easily missed, don't blame yourself ;)

**Comment by dzhou121** [comment] 2017-03-20 19:27
Thank you so much. You saved my day!

**Comment by therecipe** [comment] 2017-03-20 19:34
You are welcome :)

**Closed** 2017-07-11 02:19 UTC
